// Auto-generated by db-cli.js — BACKEND schema (trimmed).
// This is the data-shape-only counterpart to the frontend schema.js at the
// matching app/ path. It intentionally does NOT include showInList,
// profileActions, apiBase, rowLinks, customBlocks, sections, moduleRole,
// filters, or actions — those are UI concerns and live in the frontend
// schema only. Field entries also omit `label` here (UI-only display
// text) even though the frontend fields carry it. Edit
// fields/batchMutations/roles here; edit everything else there. Keep the
// `fields` array in sync between the two by regenerating both together
// (this tool writes both from the same column read).

import { resolveJoin } from '../../imsv2Schema';

export const SystemusersSchema = {
  entity: 'system_users',

  moduleRole: 'view_system_users',

  fields: [
    // key: DB column name | type: drives SQL/validation (label omitted —
    // UI-only, lives in the frontend schema)
    { key: 'primkey', type: 'number', system: true, editable: false },
    { key: 'record_id', type: 'text', system: true, editable: false },
    { key: 'name', type: 'text', title: true, required: true, searchable: true },
    { key: 'email', type: 'text', searchable: true },
    { key: 'tel', type: 'text', searchable: true },
    { key: 'ref_id', type: 'text', searchable: true },
    { key: 'regdate', type: 'datetime' },
    { key: 'user_no', type: 'text', searchable: true },
    { key: 'user_pic', type: 'text', searchable: true },
    { key: 'user_gender', type: 'text', searchable: true },
    { key: 'last_seen', type: 'text', searchable: true },
    { key: 'about', type: 'textarea', searchable: true },
    { key: 'hive_site_id', type: 'text', searchable: true },
    { key: 'hive_site_name', type: 'text', title: true, required: true, searchable: true },
    { key: 'project_id', type: 'text', searchable: true },
    { key: 'project_name', type: 'text', title: true, required: true, searchable: true },
    { key: 'user_role', type: 'text', searchable: true },
    { key: 'account_status', type: 'text', searchable: true },
    { key: 'company_id', type: 'text', searchable: true },
    { key: 'company_name', type: 'text', title: true, required: true, searchable: true },
    { key: 'clusters', type: 'textarea', searchable: true },
    { key: 'regions', type: 'textarea', searchable: true },
    { key: 'row_count', type: 'number', computed: true, editable: false },
  ],

  // Optional: joins enriching each row with data from another table.
  // Same shape as your existing *BatchMutations.js files.
  batchMutations: {
    ...resolveJoin('user_role', { as: 'role_name' }),
  },

  roles: { view: 'view_systemusers', manage: 'manage_systemusers' },
};
