// Auto-generated by db-cli.js — BACKEND schema (trimmed).
// This is the data-shape-only counterpart to the frontend schema.js at the
// matching app/ path. It intentionally does NOT include showInList,
// profileActions, apiBase, rowLinks, customBlocks, sections, moduleRole,
// filters, or actions — those are UI concerns and live in the frontend
// schema only. Field entries also omit `label` here (UI-only display
// text) even though the frontend fields carry it. Edit
// fields/batchMutations/roles here; edit everything else there. Keep the
// `fields` array in sync between the two by regenerating both together
// (this tool writes both from the same column read).

import { resolveJoin } from '../../imsv2Schema';

export const RevenueplanSchema = {
  entity: 'expected_revenue',

  moduleRole: 'view_expected_revenue',

  fields: [
    // key: DB column name | type: drives SQL/validation (label omitted —
    // UI-only, lives in the frontend schema)
    { key: 'primkey', type: 'number', system: true, editable: false },
    { key: 'record_id', type: 'text', system: true, editable: false },
    { key: 'revenue_month', type: 'text', searchable: true },
    { key: 'client_id', type: 'text', searchable: true },
    { key: 'deal_id', type: 'text', searchable: true },
    { key: 'expected_amount', type: 'money' },
    { key: 'currency_code', type: 'text', title: true, searchable: true },
    { key: 'payment_status', type: 'text', searchable: true },
    { key: 'payment_ref_no', type: 'text', searchable: true },
    { key : "collection_status", label:"Collection Type"},
    { key : "tag", label:"Collection Type"},
    { key: 'expected_close_date', type: 'datetime' },
    { key: 'probability_percent', type: 'text', searchable: true },
    { key: 'revenue_source_type', type: 'text', searchable: true },
    { key: 'revenue_title', type: 'text', searchable: true },
    { key: 'invoice_id', type: 'text', searchable: true },
    { key: 'lead_id', type: 'text', searchable: true },
    { key: 'revenue_status', type: 'text', searchable: true },
    { key: 'revenue_description', type: 'textarea', colSpan: 3, searchable: true },
    { key: 'assigned_to', type: 'text', searchable: true },
    { key: 'hive_site_id', type: 'text', searchable: true },
    { key: 'hive_site_name', type: 'text', title: true, searchable: true },
    { key: 'row_count', type: 'number', computed: true, editable: false },
  ],

  // Optional: joins enriching each row with data from another table.
  // Same shape as your existing *BatchMutations.js files.
  batchMutations: {
    ...resolveJoin('client_id', { as: 'contact_name' }),
    ...resolveJoin('deal_id', { as: 'title' }),
  },

  roles: { view: 'view_revenueplan', manage: 'manage_revenueplan' },
};
