// Auto-generated by db-cli.js — BACKEND schema (trimmed).
// This is the data-shape-only counterpart to the frontend schema.js at the
// matching app/ path. It intentionally does NOT include showInList,
// profileActions, apiBase, rowLinks, customBlocks, sections, moduleRole,
// filters, or actions — those are UI concerns and live in the frontend
// schema only. Field entries also omit `label` here (UI-only display
// text) even though the frontend fields carry it. Edit
// fields/batchMutations/roles here; edit everything else there. Keep the
// `fields` array in sync between the two by regenerating both together
// (this tool writes both from the same column read).

import { resolveJoin } from '../../imsv2Schema';

export const IncomeplanSchema = {
  entity: 'income_plan',

  moduleRole: 'view_income_plan',

  fields: [
    // key: DB column name | type: drives SQL/validation (label omitted —
    // UI-only, lives in the frontend schema)
    { key: 'primkey', type: 'number', system: true, editable: false },
    { key: 'income_plan_id', type: 'text', system: true, editable: false },
    { key: 'plan_month', type: 'datetime' },
    { key: 'income_source_id', type: 'text', searchable: true },
    { key: 'tag', type: 'text', searchable: true },
    { key: 'expected_customers', type: 'money' },
    { key: 'confidence', type: 'text', searchable: true },
    { key: 'average_deal_amount', type: 'money' },
    { key: 'actual_earnings', label: 'Actual Earnings', type: 'text', sum:true }, //actual_earnings
    { key: 'variance', label: 'Variance', type: 'text', sum:true }, //variance
    { key: 'expected_amt', type: 'textarea', searchable: true },
    { key: 'status', type: 'groupedSelect', endpoint: '/api/imsv2/incomeplan/list', groupByField: 'status', searchable: true },
    { key: 'notes', type: 'textarea', colSpan: 3, searchable: true },
    { key: 'reg_date', type: 'datetime' },
    { key: 'hive_site_id', type: 'text', searchable: true },
    { key: 'hive_site_name', type: 'text', title: true, required: true, searchable: true },
    { key: 'row_count', type: 'number', computed: true, editable: false },
  ],

  // Optional: joins enriching each row with data from another table.
  // Same shape as your existing *BatchMutations.js files.
  batchMutations: {
    ...resolveJoin('income_source_id', { as: 'name' }),
  },

  roles: { view: 'view_incomeplan', manage: 'manage_incomeplan' },
};
