// This is the ONLY file that changes when you clone this module.
// See SCHEMA-SPEC.md for the full reference — quick version below.
// Rough cut auto-generated by db-cli.js (rule-based column-name matching,
// no AI) — hand-tune sections/profileActions/groupedSelect below same as
// any other cloned module.

export const UsersledgerSchema = {
  entity: 'system_users',              // DB table name; also drives default role names
                                     // (view_usersledger / manage_usersledger) and apiBase
  label: 'Usersledger',                 // optional, defaults to entity capitalized
  apiBase: '/api/assetguard/usersledger',

  // Field keys shown as columns in list view, in display order.
  showInList: ['row_count', 'name', 'email', 'tel', 'ref_id', 'regdate', 'user_no', 'user_pic'],

  rowLinks: [],

  profileActions: [
    { key: 'back', label: 'Back to list', icon: 'arrow-left', variant: 'outline-secondary', navigateTo: '/assetguard/usersledger/list' },
    { key: 'delete', label: 'Delete', icon: 'trash', variant: 'outline-danger', confirm: 'Are you sure you want to delete this usersledger?', editOnly: true },
    { key: 'new', label: 'New Usersledger', icon: 'plus', variant: 'outline-primary', navigateTo: '/assetguard/usersledger/profile' },
    //{ key: 'clone', label: 'Clone Record', icon: 'copy', variant: 'outline-secondary', editOnly: true },
    //{ key: 'filterByDate', label: 'Filter by date', icon: 'calendar', variant: 'outline-primary' },
  ],

  fieldGroups: [],

  sections: [
    { key: 'basic_information', label: 'Basic Information', columns: 3, fields: ['name', 'email', 'tel', 'ref_id', 'regdate', 'user_no', 'user_pic'] },
    { key: 'other_details', label: 'Other Details', columns: 3, fields: ['user_gender', 'last_seen', 'about', 'hive_site_id', 'hive_site_name', 'project_id', 'project_name', 'user_role'] },
  ],

  fields: [
    // key: DB column name | label: shown on screen | type: drives input + SQL type
    { key: 'primkey', label: 'Primkey', type: 'number', system: true, editable: false },
    { key: 'record_id', label: 'Record Id', type: 'text', system: true, editable: false },
    { key: 'name', label: 'Name', type: 'text', title: true, required: true, searchable: true },
    { key: 'email', label: 'Email', type: 'text', searchable: true },
    { key: 'tel', label: 'Tel', type: 'text', searchable: true },
    { key: 'ref_id', label: 'Ref Id', type: 'text', searchable: true },
    { key: 'regdate', label: 'Regdate', type: 'datetime' },
    { key: 'user_no', label: 'User No', type: 'text', searchable: true },
    { key: 'user_pic', label: 'User Pic', type: 'text', searchable: true },
    { key: 'user_gender', label: 'User Gender', type: 'text', searchable: true },
    { key: 'last_seen', label: 'Last Seen', type: 'text', searchable: true },
    { key: 'about', label: 'About', type: 'textarea', searchable: true },
    { key: 'hive_site_id', label: 'Hive Site Id', type: 'text', searchable: true },
    { key: 'hive_site_name', label: 'Hive Site Name', type: 'text', title: true, required: true, searchable: true },
    { key: 'project_id', label: 'Project Id', type: 'text', searchable: true },
    { key: 'project_name', label: 'Project Name', type: 'text', title: true, required: true, searchable: true },
    { key: 'user_role', label: 'User Role', type: 'text', searchable: true },
    { key: 'row_count', label: '#', type: 'number', computed: true, editable: false },
    // more fields... see SCHEMA-SPEC.md for the full field option list
    // (searchable, editable, options, priority, db overrides)
  ],

  filters: [
    { key: 'all', label: 'All', query: {} },
  ],

  actions: [
    // { key: 'some_action', label: 'Do Something', appliesTo: { status: 'x' } },
    // "key" must match a function registered in lib/actionsRegistry.js
  ],

  // Optional: joins enriching each row with data from another table.
  // Same shape as your existing *BatchMutations.js files.
  batchMutations: {
    // "_staff_full_name_staff_id": {
    //   type: "join", table: "staff", link: "staff_id:record_id",
    //   select: { "_staff_full_name_staff_id": "full_name" }
    // },
  },

  // Optional: only needed if permission keys don't follow the
  // view_<entity> / manage_<entity> default.
  // roles: { view: 'view_usersledger', manage: 'manage_usersledger' },
};
