// This is the ONLY file that changes when you clone this module.
// See SCHEMA-SPEC.md for the full reference — quick version below.
// Rough cut auto-generated by db-cli.js (rule-based column-name matching,
// no AI) — hand-tune sections/profileActions/groupedSelect below same as
// any other cloned module.
//
// FRONTEND schema — full UI shape (showInList, profileActions, apiBase,
// rowLinks, customBlocks, sections, moduleRole, etc). The trimmed backend
// counterpart lives alongside this at the api/ path and only carries
// entity/fields/batchMutations/roles.

import { getApiRoutes } from '../AppRoutes/apiRoutesHandler';
// Use default base root (/)
const apiRoutes = getApiRoutes();
const moduleApi = apiRoutes.leads.base;

export const LeadsSchema = {
  entity: 'leads',              // DB table name; also drives default role names
                                     // (view_leads / manage_leads) and apiBase
  label: 'Leads',                 // optional, defaults to entity capitalized
  apiBase: moduleApi,

  //api endpint for importing data from csv
  importDataEndpoint : apiRoutes.leads.import,

  // Page-level UI gate — checked once, for the WHOLE grid AND the WHOLE
  // profile/form page, via mosyACTRLHasRole. No moduleRole set -> open to
  // anyone (same additive convention as every other role/flag in this
  // file). This is a different layer than the per-action `role` flag
  // inside individual moduleActions entries below: moduleRole controls
  // whether someone can reach the page at all; a per-action role controls
  // whether one specific button shows up once they're already in. Same
  // UI-only caveat as those: route.js needs the equivalent server-side
  // check for this to be real enforcement, not just hiding.
  moduleRole: 'view_leads',


  gridOptions : {
   checkBoxes : false,
   checkFunction : "gridCheckBoxAction"  
  },

  multiGridRows: [
    // {
    //   key: 'order_items',
    //   parentTable: 'gps_logs',
    //   title: 'Log summary',
    //   columns: [
    //     { key: 'speed', label: 'Speed' },
    //     { key: 'latitude', label: 'Lat' },
    //     { key: 'longitude', label: 'Long' , sum: true},
    //     { key: 'remark', label: 'Selling price' }
    //   ],
    //   viewMoreLink: '../gpslogs/list',
    //   filter: { order_id: '{record_id}' },
    // },
  ],

  rowLinks: [],

  // Actions available from the list view, form and grid in display order.
  //{ 
  // key: 'filter_by_client', -- name of the action 
  // label: 'Filter by account', -- button label 
  // icon: 'user', -- icon of the buttons
  // grid:true, -- show on grid or not, 
  // type: 'action', -- indicates action on form registry 
  // form: false, -- show on form or not, 
  // rowAction: false --show on row drop down or not
  // variant : 'outline-primary', -- button color  variant
  // navigateTo: '/supererpv5/revenueplan/profile', -- route to navigate to -  for link buttons only 
  // colorClass:"bg-success text-white", -- button color classname 
  // confirm: 'Are you sure you want to delete this revenueplan?', -- confirmation message for delete button
  // editOnly: true, -- show on edit only or not
  // role: 'manage_revenueplan' -- role required for this action
  //},

  profileActions: [
    { key: 'back', label: 'Back to list', icon: 'arrow-left', variant: 'outline-secondary', navigateTo: '/supererpv7/leads/list', grid: false, form: true },
    { key: 'save', label: 'Save', icon: 'save', variant: 'primary', grid: false, form: true, rowAction: false },
    { key: 'delete', label: 'Delete', icon: 'trash', variant: 'outline-danger', confirm: 'Are you sure you want to delete this lead?', editOnly: true, grid: false, form: true, rowAction: true, role: 'manage_leads' },
    { key: 'view', label: 'View more', icon: 'edit', rowAction: true },
    { key: 'new', label: 'New Lead', icon: 'plus', variant: 'outline-primary', navigateTo: '/supererpv7/leads/profile', grid: true, form: false, rowAction: false },
    { key: 'clone', label: 'Clone Record', icon: 'copy', variant: 'outline-secondary', editOnly: true, grid: false, form: true, rowAction: false, role: 'manage_leads' },
    //{ key: 'filterByDate', label: 'Filter by date', icon: 'calendar', variant: 'outline-primary', type: 'action', grid: true, form: false, rowAction: false },
  ],



  // customBlocks — the escape hatch for UI that doesn't fit the rigid
  // field-grid: a raw component, handed the SAME values/setValue/errors/
  // schema/isEditing/row context a real field gets. A block's `key` just
  // sits in a section's `fields` array exactly like a real field key —
  // wherever it appears there is where it renders. Empty by default;
  // uncomment and point at a real component when a field needs custom UI
  // (see SCHEMA-SPEC.md for the full pattern, e.g. companies/schema.js).
  customBlocks: [
    // { key: 'some_field', component: SomeComponent, colSpan: 7 },
  ],

  fieldGroups: [],
  // Field keys shown as columns in list view, in display order.
  showInList: ['row_count', 'lead_title', 'full_name', 'business_name', 'phone_number', 'alternative_phone_number', 'email_address', 'website_url'],

  //export columns these columns are used to generate upload csv template file
  exportColumns: ['lead_title', 'full_name', 'business_name', 'phone_number', 'alternative_phone_number', 'email_address', 'website_url'],

  sections: [
    { key: 'basic_information', label: 'Basic Information', columns: 3, fields: ['lead_title', 'full_name', 'business_name', 'phone_number', 'alternative_phone_number', 'email_address', 'website_url'] },
    { key: 'other_details', label: 'Other Details', columns: 3, fields: ['industry_type', 'lead_source', 'lead_status', 'converted_client_id', 'lead_temperature', 'assigned_sales_rep', 'estimated_deal_value', 'expected_conversion_date', 'country_name', 'city_name', 'business_address', 'notes', 'next_follow_up_date', 'last_contact_date', 'profile_photo'] },
  ],

  fields: [
    // key: DB column name | label: shown on screen | type: drives input + SQL type
    { key: 'primkey', label: 'Primkey', type: 'number', system: true, editable: false },
    { key: 'record_id', label: 'Record Id', type: 'text', system: true, editable: false },
    { key: 'lead_title', label: 'Lead Title', type: 'text' },
    { key: 'full_name', label: 'Full Name', type: 'text', title: true },
    { key: 'business_name', label: 'Business Name', type: 'text', title: true },
    { key: 'phone_number', label: 'Phone Number', type: 'text' },
    { key: 'alternative_phone_number', label: 'Alternative Phone Number', type: 'text' },
    { key: 'email_address', label: 'Email Address', type: 'textarea', colSpan: 3 },
    { key: 'website_url', label: 'Website Url', type: 'text' },
    { key: 'industry_type', label: 'Industry Type', type: 'text' },
    { key: 'lead_source', label: 'Lead Source', type: 'text' },
    { key: 'lead_status', label: 'Lead Status', type: 'text' },
    { key: 'converted_client_id', label: 'Converted Client Id', type: 'text' },
    { key: 'lead_temperature', label: 'Lead Temperature', type: 'text' },
    { key: 'assigned_sales_rep', label: 'Assigned Sales Rep', type: 'text' },
    { key: 'estimated_deal_value', label: 'Estimated Deal Value', type: 'money' },
    { key: 'expected_conversion_date', label: 'Expected Conversion Date', type: 'datetime' },
    { key: 'country_name', label: 'Country Name', type: 'text', title: true },
    { key: 'city_name', label: 'City Name', type: 'text', title: true },
    { key: 'business_address', label: 'Business Address', type: 'textarea', colSpan: 3 },
    { key: 'notes', label: 'Notes', type: 'textarea', colSpan: 3 },
    { key: 'next_follow_up_date', label: 'Next Follow Up Date', type: 'datetime' },
    { key: 'last_contact_date', label: 'Last Contact Date', type: 'datetime' },
    { key: 'profile_photo', label: 'Profile Photo', type: 'image' },
    { key: 'row_count', label: '#', type: 'number', computed: true, editable: false },
    //  live search field sample 
    // { key: 'permissions', label: 'Permissions',
    //   type: 'liveSearch', colSpan: 6,
    //   endpoint: '/api/assetguard/systemmodules',
    //   searchTable: 'system_modules',
    //   valueField: 'record_id',      // id column on system_modules
    //   displayField: 'module_name',  // label column on system_modules — what search results/defaultValue text actually render
    //   labelKey: 'permission_name',  // cached label already joined onto THIS row (system_roles) — only used to seed defaultValue on load
    // },
    // more fields... see SCHEMA-SPEC.md for the full field option list
    // (searchable, editable, options, priority, db overrides)
  ],

  filters: [
    { key: 'all', label: 'All', query: {} },
  ],

  actions: [
    // { key: 'some_action', label: 'Do Something', appliesTo: { status: 'x' } },
    // "key" must match a function registered in lib/actionsRegistry.js
  ],

// for button color classes  
// dyn-btn-accent-amber  { border-color: transparent; color: #b45309; }
// dyn-btn-accent-green  { border-color: transparent; color: #047857; }
// dyn-btn-accent-purple { border-color: transparent; color: #6d28d9; }
// dyn-btn-accent-pink   { border-color: transparent; color: #be185d; }
// dyn-btn-accent-red    { border-color: transparent; color: #b91c1c; }
// dyn-btn-accent-yellow { border-color: transparent; color: #a16207; }
// dyn-btn-accent-blue   { border-color: transparent; color: #1d4ed8; }
// dyn-btn-accent-teal   { border-color: transparent; color: #0f766e; }

  // Optional: only needed if permission keys don't follow the
  // view_<entity> / manage_<entity> default.
  // roles: { view: 'view_leads', manage: 'manage_leads' },
};
