// This is the ONLY file that changes when you clone this module.
// See SCHEMA-SPEC.md for the full reference — quick version below.
// Rough cut auto-generated by db-cli.js (rule-based column-name matching,
// no AI) — hand-tune sections/profileActions/groupedSelect below same as
// any other cloned module.
//
// FRONTEND schema — full UI shape (showInList, profileActions, apiBase,
// rowLinks, customBlocks, sections, moduleRole, etc). The trimmed backend
// counterpart lives alongside this at the api/ path and only carries
// entity/fields/batchMutations/roles.

import { getApiRoutes } from '../AppRoutes/apiRoutesHandler';
import { resolveField } from '../DataControl/imsv2Schema';
// Use default base root (/)
const apiRoutes = getApiRoutes();
const moduleApi = apiRoutes.revenueplan.base;

export const RevenueplanSchema = {
  entity: 'expected_revenue',              // DB table name; also drives default role names
                                     // (view_revenueplan / manage_revenueplan) and apiBase
  label: 'Expected revenue plan',                 // optional, defaults to entity capitalized
  apiBase: moduleApi,

  //api endpint for importing data from csv
  importDataEndpoint : apiRoutes.revenueplan.import,

  // Page-level UI gate — checked once, for the WHOLE grid AND the WHOLE
  // profile/form page, via mosyACTRLHasRole. No moduleRole set -> open to
  // anyone (same additive convention as every other role/flag in this
  // file). This is a different layer than the per-action `role` flag
  // inside individual moduleActions entries below: moduleRole controls
  // whether someone can reach the page at all; a per-action role controls
  // whether one specific button shows up once they're already in. Same
  // UI-only caveat as those: route.js needs the equivalent server-side
  // check for this to be real enforcement, not just hiding.
  moduleRole: 'view_revenueplan',


  gridOptions : {
   checkBoxes : false,
   checkFunction : "gridCheckBoxAction"  
  },

  multiGridRows: [
    // {
    //   key: 'order_items',
    //   parentTable: 'gps_logs',
    //   title: 'Log summary',
    //   columns: [
    //     { key: 'speed', label: 'Speed' },
    //     { key: 'latitude', label: 'Lat' },
    //     { key: 'longitude', label: 'Long' , sum: true},
    //     { key: 'remark', label: 'Selling price' }
    //   ],
    //   viewMoreLink: '../gpslogs/list',
    //   filter: { order_id: '{record_id}' },
    // },
  ],

  rowLinks: [],

  // Actions available from the list view, form and grid in display order.
  //{ 
  // key: 'filter_by_client', -- name of the action 
  // label: 'Filter by account', -- button label 
  // icon: 'user', -- icon of the buttons
  // grid:true, -- show on grid or not, 
  // type: 'action', -- indicates action on form registry 
  // form: false, -- show on form or not, 
  // rowAction: false --show on row drop down or not
  // variant : 'outline-primary', -- button color  variant
  // navigateTo: '/supererpv5/revenueplan/profile', -- route to navigate to -  for link buttons only 
  // colorClass:"bg-success text-white", -- button color classname 
  // confirm: 'Are you sure you want to delete this revenueplan?', -- confirmation message for delete button
  // editOnly: true, -- show on edit only or not
  // role: 'manage_revenueplan' -- role required for this action
  //},

  profileActions: [
    { key: 'back', label: 'Back to list', icon: 'arrow-left', variant: 'outline-secondary', navigateTo: '/imsv2/revenueplan/list', grid: false, form: true },
    { key: 'save', label: 'Save', icon: 'save', variant: 'primary', grid: false, form: true, rowAction: false },
    { key: 'delete', label: 'Delete', icon: 'trash', variant: 'outline-danger', confirm: 'Are you sure you want to delete this revenueplan?', editOnly: true, grid: false, form: true, rowAction: true, role: 'manage_revenueplan' },
    { key: 'view', label: 'View more', icon: 'edit', rowAction: true },
    { key: 'new', label: 'Add new', icon: 'file-text', variant: 'outline-primary', navigateTo: '/imsv2/revenueplan/profile', grid: true, form: false, rowAction: false },
    { key: 'clone', label: 'Clone Record', icon: 'copy', variant: 'outline-secondary', editOnly: true, grid: false, form: true, rowAction: false, role: 'manage_revenueplan' },
    //{ key: 'filterByDate', label: 'Filter by date', icon: 'calendar', variant: 'outline-primary', type: 'action', grid: true, form: false, rowAction: false },

    // Contact-touch actions — route through logicControl/actionsRegistry.js.
    { key: 'call', label: 'Call', icon: 'phone', variant: 'outline-success', type: 'action', editOnly: true, grid: false, form: true, rowAction: true },
    { key: 'send_message', label: 'Send Message', icon: 'comment', variant: 'outline-primary', type: 'action', editOnly: true, grid: false, form: true, rowAction: true },
    { key: 'set_reminder', label: 'Set Reminder', icon: 'bell', variant: 'outline-primary', type: 'action', editOnly: true, grid: false, form: true},
    { key: 'request_payment', label: 'Request Payment', icon: 'money', variant: 'outline-info', type: 'action', editOnly: true, grid: false, form: true },
    { key: 'record_payment', label: 'Record Payment', icon: 'credit-card', variant: 'outline-success', type: 'action', editOnly: true, grid: false, form: true, rowAction: true },
    { key: 'add_deal', label: 'Create Deal', icon: 'handshake-o', variant: 'outline-warning', type: 'action', editOnly: true, grid: false, form: true },
    { key: 'add_activity', label: 'Add Activity', icon: 'calendar-plus-o', variant: 'outline-warning', type: 'action', editOnly: true, grid: false, form: true},

    // Related-record popups — scoped to this plan's linked client (call/
    // message history) or to this plan's own record (reminders, which
    // follow the same self-referencing convention set_reminder above uses).
    { key: 'view_payment_history', label: 'Payment History', icon: 'money', variant: 'outline-secondary', type: 'action', editOnly: true, grid: false, form: true, rowAction: true },
    { key: 'view_call_history', label: 'Call History', icon: 'history', variant: 'outline-secondary', type: 'action', editOnly: true, grid: false, form: true, rowAction: true },
    { key: 'view_message_history', label: 'Message History', icon: 'comments-o', variant: 'outline-secondary', type: 'action', editOnly: true, grid: false, form: true, rowAction: true },
    { key: 'view_reminders', label: 'Reminders', icon: 'bell', variant: 'outline-secondary', type: 'action', editOnly: true, grid: false, form: true, rowAction: true },
    { key: 'view_activities', label: 'Activities', icon: 'calendar-check-o', variant: 'outline-secondary', type: 'action', editOnly: true, grid: false, form: true},

    // Grid-toolbar smart filters — client picks a row from the Contacts
    // module and scopes by this table's own client_id FK, status/month
    // pick from this table's own distinct values.
    { key: 'filter_by_client', label: 'Filter by Client', icon: 'user', variant: 'outline-secondary', type: 'action', grid: true, form: false, rowAction: false },
    { key: 'filter_by_status', label: 'Filter by Status', icon: 'filter', variant: 'outline-secondary', type: 'action', grid: true, form: false, rowAction: false },
    { key: 'filter_by_month', label: 'Filter by Month', icon: 'calendar', variant: 'outline-secondary', type: 'action', grid: true, form: false, rowAction: false },
  ],



  // customBlocks — the escape hatch for UI that doesn't fit the rigid
  // field-grid: a raw component, handed the SAME values/setValue/errors/
  // schema/isEditing/row context a real field gets. A block's `key` just
  // sits in a section's `fields` array exactly like a real field key —
  // wherever it appears there is where it renders. Empty by default;
  // uncomment and point at a real component when a field needs custom UI
  // (see SCHEMA-SPEC.md for the full pattern, e.g. companies/schema.js).
  customBlocks: [
    // { key: 'some_field', component: SomeComponent, colSpan: 7 },
  ],

  fieldGroups: [],
  // Field keys shown as columns in list view, in display order.
  showInList: ['row_count', 'revenue_month', 'contact_name', 'title', 'expected_amount', 'payment_status', 'payment_ref_no','collection_status'],

  //export columns these columns are used to generate upload csv template file
  exportColumns: ['revenue_month', 'client_id', 'deal_id', 'expected_amount', 'payment_status', 'payment_ref_no'],

  sections: [
    { key: 'basic_information', label: 'Basic Information', columns: 3, fields: ['revenue_month', 'client_id', 'deal_id', 'expected_amount', 'payment_status', 'collection_status', 'payment_ref_no', 'revenue_description',] },
   ],

  fields: [
    // key: DB column name | label: shown on screen | type: drives input + SQL type
    { key: 'primkey', label: 'Primkey', type: 'number', system: true, editable: false },
    { key: 'record_id', label: 'Record Id', type: 'text', system: true, editable: false },
    { key: 'revenue_month', label: 'Revenue Month', type: 'groupedSelect' , endpoint:moduleApi, title:true },
    ...resolveField('client_id', { as: 'contact_name', colSpan:4 }),
    ...resolveField('deal_id', { as: 'title', colSpan:4 }),
    {key : "title", type:"text", title:true,  computed: true, editable: false},
    {key : "contact_name", label:"Contact Name", type:"text", title:true,  computed: true, editable: false},
    {key : "collection_status", label:"Collection Type", type:"groupedSelect", title:true,  endpoint:moduleApi},
    { key: 'expected_amount', label: 'Expected Amount', type: 'money' , sum:true },
    { key: 'currency_code', label: 'Currency Code', type: 'text' },
    { key: 'payment_status', label: 'Payment Status', type: 'select' , options: ['Paid', 'Unpaid', 'Partially Paid'] },
    { key: 'payment_ref_no', label: 'Payment Ref No', type: 'text' },
    { key: 'expected_close_date', label: 'Expected Close Date', type: 'datetime' },
    { key: 'probability_percent', label: 'Probability Percent', type: 'text' },
    { key: 'revenue_source_type', label: 'Revenue Source Type', type: 'text' },
    { key: 'revenue_title', label: 'Revenue Title', type: 'text' },
    { key: 'invoice_id', label: 'Invoice Id', type: 'text' },
    { key: 'lead_id', label: 'Lead Id', type: 'text' },
    { key: 'revenue_status', label: 'Revenue Status', type: 'text' },
    { key: 'revenue_description', label: 'Revenue Description', type: 'textarea', colSpan: 12 },
    { key: 'assigned_to', label: 'Assigned To', type: 'text' },
    { key: 'row_count', label: '#', type: 'number', computed: true, editable: false },
    //  live search field sample 
    // { key: 'permissions', label: 'Permissions',
    //   type: 'liveSearch', colSpan: 6,
    //   endpoint: '/api/assetguard/systemmodules',
    //   searchTable: 'system_modules',
    //   valueField: 'record_id',      // id column on system_modules
    //   displayField: 'module_name',  // label column on system_modules — what search results/defaultValue text actually render
    //   labelKey: 'permission_name',  // cached label already joined onto THIS row (system_roles) — only used to seed defaultValue on load
    // },
    // more fields... see SCHEMA-SPEC.md for the full field option list
    // (searchable, editable, options, priority, db overrides)
  ],

  filters: [
    { key: 'all', label: 'All', query: {} },
  ],

  actions: [
    // { key: 'some_action', label: 'Do Something', appliesTo: { status: 'x' } },
    // "key" must match a function registered in lib/actionsRegistry.js
  ],

// for button color classes  
// dyn-btn-accent-amber  { border-color: transparent; color: #b45309; }
// dyn-btn-accent-green  { border-color: transparent; color: #047857; }
// dyn-btn-accent-purple { border-color: transparent; color: #6d28d9; }
// dyn-btn-accent-pink   { border-color: transparent; color: #be185d; }
// dyn-btn-accent-red    { border-color: transparent; color: #b91c1c; }
// dyn-btn-accent-yellow { border-color: transparent; color: #a16207; }
// dyn-btn-accent-blue   { border-color: transparent; color: #1d4ed8; }
// dyn-btn-accent-teal   { border-color: transparent; color: #0f766e; }

  // Optional: only needed if permission keys don't follow the
  // view_<entity> / manage_<entity> default.
  // roles: { view: 'view_revenueplan', manage: 'manage_revenueplan' },
};
