// This is the ONLY file that changes when you clone this module.
// See SCHEMA-SPEC.md for the full reference — quick version below.
// Rough cut auto-generated by db-cli.js (rule-based column-name matching,
// no AI) — hand-tune sections/profileActions/groupedSelect below same as
// any other cloned module.
//
// FRONTEND schema — full UI shape (showInList, profileActions, apiBase,
// rowLinks, customBlocks, sections, moduleRole, etc). The trimmed backend
// counterpart lives alongside this at the api/ path and only carries
// entity/fields/batchMutations/roles.

import { getApiRoutes } from '../AppRoutes/apiRoutesHandler';
import { resolveField } from '../DataControl/imsv2Schema';
// Use default base root (/)
const apiRoutes = getApiRoutes();
const moduleApi = apiRoutes.incomeplan.base;

export const IncomeplanSchema = {
  entity: 'income_plan',              // DB table name; also drives default role names
                                     // (view_incomeplan / manage_incomeplan) and apiBase
  label: 'Income plan',                 // optional, defaults to entity capitalized
  apiBase: moduleApi,

  //api endpint for importing data from csv
  importDataEndpoint : apiRoutes.incomeplan.import,

  // Page-level UI gate — checked once, for the WHOLE grid AND the WHOLE
  // profile/form page, via mosyACTRLHasRole. No moduleRole set -> open to
  // anyone (same additive convention as every other role/flag in this
  // file). This is a different layer than the per-action `role` flag
  // inside individual moduleActions entries below: moduleRole controls
  // whether someone can reach the page at all; a per-action role controls
  // whether one specific button shows up once they're already in. Same
  // UI-only caveat as those: route.js needs the equivalent server-side
  // check for this to be real enforcement, not just hiding.
  moduleRole: 'view_incomeplan',


  gridOptions : {
   checkBoxes : false,
   checkFunction : "gridCheckBoxAction"  
  },

  multiGridRows: [
    // {
    //   key: 'order_items',
    //   parentTable: 'gps_logs',
    //   title: 'Log summary',
    //   columns: [
    //     { key: 'speed', label: 'Speed' },
    //     { key: 'latitude', label: 'Lat' },
    //     { key: 'longitude', label: 'Long' , sum: true},
    //     { key: 'remark', label: 'Selling price' }
    //   ],
    //   viewMoreLink: '../gpslogs/list',
    //   filter: { order_id: '{record_id}' },
    // },
  ],

  rowLinks: [],

  // Actions available from the list view, form and grid in display order.
  //{ 
  // key: 'filter_by_client', -- name of the action 
  // label: 'Filter by account', -- button label 
  // icon: 'user', -- icon of the buttons
  // grid:true, -- show on grid or not, 
  // type: 'action', -- indicates action on form registry 
  // form: false, -- show on form or not, 
  // rowAction: false --show on row drop down or not
  // variant : 'outline-primary', -- button color  variant
  // navigateTo: '/supererpv5/revenueplan/profile', -- route to navigate to -  for link buttons only 
  // colorClass:"bg-success text-white", -- button color classname 
  // confirm: 'Are you sure you want to delete this revenueplan?', -- confirmation message for delete button
  // editOnly: true, -- show on edit only or not
  // role: 'manage_revenueplan' -- role required for this action
  //},

  profileActions: [
    { key: 'back', label: 'Back to list', icon: 'arrow-left', variant: 'outline-secondary', navigateTo: '/imsv2/incomeplan/list', grid: false, form: true },
    { key: 'save', label: 'Save', icon: 'save', variant: 'primary', grid: false, form: true, rowAction: false },
    { key: 'delete', label: 'Delete', icon: 'trash', variant: 'outline-danger', confirm: 'Are you sure you want to delete this incomeplan?', editOnly: true, grid: false, form: true, rowAction: true, role: 'manage_incomeplan' },
    { key: 'view', label: 'View more', icon: 'edit', rowAction: true },
    { key: 'new', label: 'New Income plan', icon: 'plus', variant: 'outline-primary', navigateTo: '/imsv2/incomeplan/profile', grid: true, form: false, rowAction: false },
    { key: 'clone', label: 'Clone Record', icon: 'copy', variant: 'outline-secondary', editOnly: true, grid: false, form: true, rowAction: false, role: 'manage_incomeplan' },
    //{ key: 'filterByDate', label: 'Filter by date', icon: 'calendar', variant: 'outline-primary', type: 'action', grid: true, form: false, rowAction: false },

    // Activities/Deals have no FK back to income plan — both scope by a
    // shared `tag` column instead (e.g. "Aug-2026", derived from this
    // plan's own plan_month) — see actionsRegistry.js's tagFromPlan().
    // Payment History still scopes by real date range (payment_date).
    { key: 'add_activity', label: 'Add Activity', icon: 'calendar-plus-o', variant: 'outline-warning', type: 'action', editOnly: true, grid: false, form: true, rowAction: true },
    { key: 'view_activities', label: 'Activities', icon: 'calendar-check-o', variant: 'outline-secondary', type: 'action', editOnly: true, grid: false, form: true, rowAction: true },

    { key: 'add_deal', label: 'Create Deal', icon: 'handshake-o', variant: 'outline-warning', type: 'action', editOnly: true, grid: false, form: true, rowAction: true },
    { key: 'view_deals', label: 'Deals', icon: 'briefcase', variant: 'outline-secondary', type: 'action', editOnly: true, grid: false, form: true, rowAction: true },
    { key : 'filter_by_tag', label: 'Filter by Tag', icon: 'tags', variant: 'outline-secondary', type: 'action', grid: true, form: false, rowAction: false },
    { key : 'filter_by_status', label: 'Filter by Status', icon: 'info', variant: 'outline-secondary', type: 'action', grid: true, form: false, rowAction: false },
    { key : 'filter_by_month', label: 'Filter by Month', icon: 'calendar', variant: 'outline-secondary', type: 'action', grid: true, form: false, rowAction: false },

    { key: 'view_payment_history', label: 'Payment History', icon: 'money', variant: 'outline-secondary', type: 'action', editOnly: true, grid: false, form: true, rowAction: true },
  ],



  // customBlocks — the escape hatch for UI that doesn't fit the rigid
  // field-grid: a raw component, handed the SAME values/setValue/errors/
  // schema/isEditing/row context a real field gets. A block's `key` just
  // sits in a section's `fields` array exactly like a real field key —
  // wherever it appears there is where it renders. Empty by default;
  // uncomment and point at a real component when a field needs custom UI
  // (see SCHEMA-SPEC.md for the full pattern, e.g. companies/schema.js).
  customBlocks: [
    // { key: 'some_field', component: SomeComponent, colSpan: 7 },
  ],

  fieldGroups: [],
  // Field keys shown as columns in list view, in display order.
  showInList: ['row_count', 'plan_month', 'name', 'expected_customers', 'tag','average_deal_amount', 'expected_amt', 'actual_earnings', 'variance','status','notes'],

  //export columns these columns are used to generate upload csv template file
  exportColumns: ['plan_month', 'income_source_id', 'expected_customers', 'average_deal_amount', 'expected_amt', 'status', 'notes'],

  sections: [
    { key: 'basic_information', label: 'Basic Information', columns: 3, fields: ['plan_month', 'income_source_id', 'tag', 'expected_customers', 'average_deal_amount', 'expected_amt', 'actual_earnings', 'variance', 'notes'] },
    { key: 'other_details', label: 'Other Details', columns: 3, fields: ['status','reg_date'] },
  ],

  fields: [
    // key: DB column name | label: shown on screen | type: drives input + SQL type
    { key: 'primkey', label: 'Primkey', type: 'number', system: true, editable: false },
    { key: 'income_plan_id', label: 'Income Plan Id', type: 'text', system: true, editable: false },
    { key: 'plan_month', label: 'Plan Month', type: 'groupedSelect', endpoint: moduleApi, title: true, groupByField: 'plan_month',colSpan: 6 },
    ...resolveField('income_source_id', { as: 'name' }),
    {key: 'name', label: 'Name', type: 'text', title: true,  computed: true, editable: false},
    { key: 'expected_customers', label: 'Expected Customers', type: 'text', sum:true },
    { key : "tag", label:"Tag", type:"groupedSelect", title:true,  endpoint:moduleApi},
    { key: 'average_deal_amount', label: 'Average Deal Amount', type: 'money' , sum:true },
    { key: 'expected_amt', label: 'Expected Amt', type: 'text' , sum:true , title: true, editable: false},
    { key: 'status', label: 'Status', type: 'groupedSelect', endpoint: moduleApi, groupByField: 'status' },
    { key: 'notes', label: 'Notes', type: 'textarea', colSpan: 12 },
    { key: 'actual_earnings', label: 'Actual Earnings', type: 'text', sum:true }, //actual_earnings
    { key: 'variance', label: 'Variance', type: 'text', sum:true, editable: false }, //variance
    { key: 'reg_date', label: 'Reg Date', type: 'datetime', editable: false },
    { key: 'row_count', label: '#', type: 'number', computed: true, editable: false },
    //  live search field sample 
    // { key: 'permissions', label: 'Permissions',
    //   type: 'liveSearch', colSpan: 6,
    //   endpoint: '/api/assetguard/systemmodules',
    //   searchTable: 'system_modules',
    //   valueField: 'record_id',      // id column on system_modules
    //   displayField: 'module_name',  // label column on system_modules — what search results/defaultValue text actually render
    //   labelKey: 'permission_name',  // cached label already joined onto THIS row (system_roles) — only used to seed defaultValue on load
    // },
    // more fields... see SCHEMA-SPEC.md for the full field option list
    // (searchable, editable, options, priority, db overrides)
  ],

  filters: [
    { key: 'all', label: 'All', query: {} },
  ],

  actions: [
    // { key: 'some_action', label: 'Do Something', appliesTo: { status: 'x' } },
    // "key" must match a function registered in lib/actionsRegistry.js
  ],

  // Smart-compute listener — see FormEngine.jsx's setValue for the hook
  // this plugs into. Keying in expected_customers/average_deal_amount
  // auto-fills expected_amt (customers * deal size); once actual_earnings
  // is also keyed in, variance (actual - expected) follows along too.
  // Recomputed from ALL three fields on every keystroke to any of them, so
  // editing an earlier field after the fact keeps expected_amt/variance in
  // sync instead of going stale.
  computeOnChange: (changedKey, values) => {
    if (!['expected_customers', 'average_deal_amount', 'actual_earnings'].includes(changedKey)) {
      return null;
    }

    const customers = parseFloat(values.expected_customers) || 0;
    const avgDealAmount = parseFloat(values.average_deal_amount) || 0;
    const expectedAmt = customers * avgDealAmount;

    const patch = { expected_amt: expectedAmt ? String(expectedAmt) : '' };

    const hasActual = values.actual_earnings !== '' && values.actual_earnings !== null && values.actual_earnings !== undefined;
    patch.variance = hasActual ? String((parseFloat(values.actual_earnings) || 0) - expectedAmt) : '';

    return patch;
  },

// for button color classes  
// dyn-btn-accent-amber  { border-color: transparent; color: #b45309; }
// dyn-btn-accent-green  { border-color: transparent; color: #047857; }
// dyn-btn-accent-purple { border-color: transparent; color: #6d28d9; }
// dyn-btn-accent-pink   { border-color: transparent; color: #be185d; }
// dyn-btn-accent-red    { border-color: transparent; color: #b91c1c; }
// dyn-btn-accent-yellow { border-color: transparent; color: #a16207; }
// dyn-btn-accent-blue   { border-color: transparent; color: #1d4ed8; }
// dyn-btn-accent-teal   { border-color: transparent; color: #0f766e; }

  // Optional: only needed if permission keys don't follow the
  // view_<entity> / manage_<entity> default.
  // roles: { view: 'view_incomeplan', manage: 'manage_incomeplan' },
};
