// This is the ONLY file that changes when you clone this module.
// See SCHEMA-SPEC.md for the full reference — quick version below.
// Rough cut auto-generated by db-cli.js (rule-based column-name matching,
// no AI) — hand-tune sections/profileActions/groupedSelect below same as
// any other cloned module.

export const SystemusersSchema = {
  entity: 'system_users',              // DB table name; also drives default role names
                                     // (view_systemusers / manage_systemusers) and apiBase
  label: 'Systemusers',                 // optional, defaults to entity capitalized
  apiBase: '/api/assetguard/systemusers',

  // Page-level UI gate — checked once, for the WHOLE grid AND the WHOLE
  // profile/form page, via mosyACTRLHasRole. No moduleRole set -> open to
  // anyone (same additive convention as every other role/flag in this
  // file). This is a different layer than the per-action `role` flag
  // inside individual moduleActions entries below: moduleRole controls
  // whether someone can reach the page at all; a per-action role controls
  // whether one specific button shows up once they're already in. Same
  // UI-only caveat as those: route.js needs the equivalent server-side
  // check for this to be real enforcement, not just hiding.
  moduleRole: 'view_systemusers',

  // Field keys shown as columns in list view, in display order.
  showInList: ['row_count', 'name', 'email', 'tel', 'ref_id', 'regdate', 'user_no', 'user_pic'],

  rowLinks: [],

  // profileActions — one array, three possible places each entry can
  // render, spelled out explicitly on every entry (no implicit
  // defaults): the grid, DynamicForm.jsx, and EntityRowOptions' dropdown
  // all read this SAME array, each filtering on its own flag. Comment an
  // entry out, or flip a flag to false, and it disappears from that one
  // place — no component edit needed.
  //   grid: true/false      -> grid toolbar (list page)
  //   form: true/false      -> profile/form toolbar ('save' is also the
  //                            primary submit button — DynamicForm picks
  //                            the submit button as whichever entry has
  //                            both form:true and key:'save')
  //   rowAction: true/false -> per-row dropdown in the grid (EntityRowOptions)
  //   editOnly: true        -> only shown once a record exists (form/rowAction contexts)
  //   role: 'role_name'     -> UI-ONLY gate, checked via mosyACTRLHasRole
  //                            (session roles from localStorage). Omit
  //                            entirely and the action is open to anyone —
  //                            this is additive, not a default-deny system.
  //                            NOTE: this does not by itself stop the
  //                            request server-side — route.js currently
  //                            gates every mutation behind one blanket
  //                            manage_<entity> role regardless of which
  //                            action triggered it. Real enforcement needs
  //                            the same per-action role checked there too.
  profileActions: [
    { key: 'back', label: 'Back to list', icon: 'arrow-left', variant: 'outline-secondary', navigateTo: '/assetguard/systemusers/list', grid: false, form: true },
    { key: 'save', label: 'Save', icon: 'save', variant: 'primary', grid: false, form: true, rowAction: false },
    { key: 'delete', label: 'Delete', icon: 'trash', variant: 'outline-danger', confirm: 'Are you sure you want to delete this systemuser?', editOnly: true, grid: false, form: true, rowAction: true, role: 'manage_systemusers' },
    { key: 'view', label: 'View more', icon: 'edit', rowAction: true },
    { key: 'new', label: 'New Systemuser', icon: 'plus', variant: 'outline-primary', navigateTo: '/assetguard/systemusers/profile', grid: true, form: false, rowAction: false },
    //{ key: 'clone', label: 'Clone Record', icon: 'copy', variant: 'outline-secondary', editOnly: true, grid: false, form: true, rowAction: false, role: 'manage_systemusers' },
    //{ key: 'filterByDate', label: 'Filter by date', icon: 'calendar', variant: 'outline-primary', type: 'action', grid: true, form: false, rowAction: false },
  ],

  // customBlocks — the escape hatch for UI that doesn't fit the rigid
  // field-grid: a raw component, handed the SAME values/setValue/errors/
  // schema/isEditing/row context a real field gets. A block's `key` just
  // sits in a section's `fields` array exactly like a real field key —
  // wherever it appears there is where it renders. Empty by default;
  // uncomment and point at a real component when a field needs custom UI
  // (see SCHEMA-SPEC.md for the full pattern, e.g. companies/schema.js).
  customBlocks: [
    // { key: 'some_field', component: SomeComponent, colSpan: 7 },
  ],

  fieldGroups: [],

  sections: [
    { key: 'basic_information', label: 'Basic Information', columns: 3, fields: ['name', 'email', 'tel', 'ref_id', 'regdate', 'user_no', 'user_pic'] },
    { key: 'other_details', label: 'Other Details', columns: 3, fields: ['user_gender', 'last_seen', 'about', 'hive_site_id', 'hive_site_name', 'project_id', 'project_name', 'user_role', 'account_status', 'company_id', 'company_name'] },
  ],

  fields: [
    // key: DB column name | label: shown on screen | type: drives input + SQL type
    { key: 'primkey', label: 'Primkey', type: 'number', system: true, editable: false },
    { key: 'record_id', label: 'Record Id', type: 'text', system: true, editable: false },
    { key: 'name', label: 'Name', type: 'text', title: true, required: true, searchable: true },
    { key: 'email', label: 'Email', type: 'text', searchable: true },
    { key: 'tel', label: 'Tel', type: 'text', searchable: true },
    { key: 'ref_id', label: 'Ref Id', type: 'text', searchable: true },
    { key: 'regdate', label: 'Regdate', type: 'datetime' },
    { key: 'user_no', label: 'User No', type: 'text', searchable: true },
    { key: 'user_pic', label: 'User Pic', type: 'image', searchable: true },
    { key: 'user_gender', label: 'User Gender', type: 'text', searchable: true },
    { key: 'last_seen', label: 'Last Seen', type: 'text', searchable: true },
    { key: 'about', label: 'About', type: 'textarea', searchable: true },
    { key: 'hive_site_id', label: 'Hive Site Id', type: 'text', searchable: true },
    { key: 'hive_site_name', label: 'Hive Site Name', type: 'text', title: true, required: true, searchable: true },
    { key: 'project_id', label: 'Project Id', type: 'text', searchable: true },
    { key: 'project_name', label: 'Project Name', type: 'text', title: true, required: true, searchable: true },
    { key: 'user_role', label: 'User Role', type: 'text', searchable: true },
    { key: 'role_name', computed:true},
    { key: 'regions' , searchable:true},
    { key: 'clusters', searchable:true},
    { key: 'account_status', label: 'Account Status', type: 'text', searchable: true },
    { key: 'company_id', label: 'Company Id', type: 'text', searchable: true },
    { key: 'company_label', label: 'Company Name', type: 'text', title: true, computed: true, searchable: true },
    { key: 'row_count', label: '#', type: 'number', computed: true, editable: false },
    // more fields... see SCHEMA-SPEC.md for the full field option list
    // (searchable, editable, options, priority, db overrides)
  ],

  filters: [
    { key: 'all', label: 'All', query: {} },
  ],

  actions: [
    // { key: 'some_action', label: 'Do Something', appliesTo: { status: 'x' } },
    // "key" must match a function registered in lib/actionsRegistry.js
  ],

  // Optional: joins enriching each row with data from another table.
  // Same shape as your existing *BatchMutations.js files.
  batchMutations: {
    "role_name": {
      type: "join", table: "system_roles", link: "user_role:record_id",
      select: { "role_name": "role_name" }
    },
    "company_label": {
      type: "join", table: "companies", link: "company_id:company_id",
      select: { "company_label": "company_name" }
    },
  },

  // Optional: only needed if permission keys don't follow the
  // view_<entity> / manage_<entity> default.
  // roles: { view: 'view_systemusers', manage: 'manage_systemusers' },
};
