// Auto-generated by db-cli.js — BACKEND schema (trimmed).
// This is the data-shape-only counterpart to the frontend schema.js at the
// matching app/ path. It intentionally does NOT include showInList,
// profileActions, apiBase, rowLinks, customBlocks, sections, moduleRole,
// filters, or actions — those are UI concerns and live in the frontend
// schema only. Field entries also omit `label` here (UI-only display
// text) even though the frontend fields carry it. Edit
// fields/batchMutations/roles here; edit everything else there. Keep the
// `fields` array in sync between the two by regenerating both together
// (this tool writes both from the same column read).

import { resolveJoin } from '../../imsv2Schema';

export const OpportunitiesSchema = {
  entity: 'opportunities',

  moduleRole: 'view_opportunities',

  fields: [
    // key: DB column name | type: drives SQL/validation (label omitted —
    // UI-only, lives in the frontend schema)
    { key: 'primkey', type: 'number', system: true, editable: false },
    { key: 'opportunity_id', type: 'text', system: true, editable: false },
    { key: 'contact_id', type: 'text', searchable: true },
    { key: 'title', type: 'text', searchable: true },
    { key: 'description', type: 'textarea', colSpan: 12, searchable: true },
    { key: 'type', type: 'select', searchable: true },
    { key: 'stage', type: 'select', searchable: true },
    { key: 'amount', type: 'money' },
    { key: 'currency', type: 'select', searchable: true },
    { key: 'expected_date', type: 'datetime' },
    { key: 'tag', type: 'groupedSelect', endpoint: '/api/imsv2/opportunities/list', groupByField: 'tag', searchable: true },
    { key: 'next_action', type: 'text', searchable: true },
    { key: 'next_action_date', type: 'datetime' },
    { key: 'status', type: 'groupedSelect', endpoint: '/api/imsv2/opportunities/list', groupByField: 'status', searchable: true },
    { key: 'reg_date', type: 'datetime' },
    { key: 'hive_site_id', type: 'text', searchable: true },
    { key: 'hive_site_name', type: 'text', title: true, required: true, searchable: true },
    { key: 'row_count', type: 'number', computed: true, editable: false },
  ],

  // Optional: joins enriching each row with data from another table.
  // Same shape as your existing *BatchMutations.js files.
  batchMutations: {
    ...resolveJoin('contact_id', { as: 'contact_name' }),
  },

  roles: { view: 'view_opportunities', manage: 'manage_opportunities' },
};
