// Auto-generated by db-cli.js — BACKEND schema (trimmed).
// This is the data-shape-only counterpart to the frontend schema.js at the
// matching app/ path. It intentionally does NOT include showInList,
// profileActions, apiBase, rowLinks, customBlocks, sections, moduleRole,
// filters, or actions — those are UI concerns and live in the frontend
// schema only. Field entries also omit `label` here (UI-only display
// text) even though the frontend fields carry it. Edit
// fields/batchMutations/roles here; edit everything else there. Keep the
// `fields` array in sync between the two by regenerating both together
// (this tool writes both from the same column read).

export const MosyremindersSchema = {
  entity: 'mosy_reminders',

  moduleRole: 'view_mosy_reminders',

  fields: [
    // key: DB column name | type: drives SQL/validation (label omitted —
    // UI-only, lives in the frontend schema)
    { key: 'primkey', type: 'number', system: true, editable: false },
    { key: 'reminder_id', type: 'text', system: true, editable: false },
    { key: 'tenant_id', type: 'text', searchable: true },
    { key: 'app_name', type: 'text', title: true, required: true, searchable: true },
    { key: 'related_record_id', type: 'text', editable: false, searchable: true },
    { key: 'time_of_day', type: 'text', searchable: true },
    { key: 'days_of_week', type: 'text', searchable: true },
    { key: 'repeat_type', type: 'text', searchable: true },
    { key: 'recipients_phone', type: 'textarea', searchable: true },
    { key: 'recipients_email', type: 'textarea', searchable: true },
    { key: 'subject', type: 'text', searchable: true },
    { key: 'message', type: 'textarea', colSpan: 3, searchable: true },
    { key: 'variable_source', type: 'text', searchable: true },
    { key: 'last_sent_date', type: 'datetime' },
    { key: 'status', type: 'groupedSelect', endpoint: '/api/imsv2/mosyreminders/list', groupByField: 'status', searchable: true },
    { key: 'reg_date', type: 'datetime' },
    { key: 'row_count', type: 'number', computed: true, editable: false },
  ],

  // Optional: joins enriching each row with data from another table.
  // Same shape as your existing *BatchMutations.js files.
  batchMutations: {
    // "_staff_full_name_staff_id": {
    //   type: "join", table: "staff", link: "staff_id:record_id",
    //   select: { "_staff_full_name_staff_id": "full_name" }
    // },
  },

  roles: { view: 'view_mosyreminders', manage: 'manage_mosyreminders' },
};
