// Auto-generated by db-cli.js — BACKEND schema (trimmed).
// This is the data-shape-only counterpart to the frontend schema.js at the
// matching app/ path. It intentionally does NOT include showInList,
// profileActions, apiBase, rowLinks, customBlocks, sections, moduleRole,
// filters, or actions — those are UI concerns and live in the frontend
// schema only. Field entries also omit `label` here (UI-only display
// text) even though the frontend fields carry it. Edit
// fields/batchMutations/roles here; edit everything else there. Keep the
// `fields` array in sync between the two by regenerating both together
// (this tool writes both from the same column read).

import { resolveJoin } from '../../imsv2Schema';

export const MessagetemplatesSchema = {
  entity: 'smart_message_templates',

  moduleRole: 'view_smart_message_templates',

  fields: [
    // key: DB column name | type: drives SQL/validation (label omitted —
    // UI-only, lives in the frontend schema)
    { key: 'primkey', type: 'number', system: true, editable: false },
    { key: 'record_id', type: 'text', system: true, editable: false },
    { key: 'template_name', type: 'text', title: true, searchable: true },
    { key: 'template_code', type: 'text', title: true, searchable: true },
    { key: 'template_category', type: 'text', searchable: true },
    { key: 'message_channel', type: 'textarea', colSpan: 3, searchable: true },
    { key: 'subject', type: 'text', searchable: true },
    { key: 'message_content', type: 'textarea', colSpan: 3, searchable: true },
    { key: 'template_status', type: 'text', searchable: true },
    { key: 'created_by', type: 'text', searchable: true },
    { key: 'last_updated_by', type: 'datetime' },
    { key: 'created_on', type: 'datetime' },
    { key: 'updated_on', type: 'datetime' },
    { key: 'hive_site_id', type: 'text', searchable: true },
    { key: 'hive_site_name', type: 'text', title: true, searchable: true },
    { key: 'row_count', type: 'number', computed: true, editable: false },
  ],

  // Optional: joins enriching each row with data from another table.
  // Same shape as your existing *BatchMutations.js files.
  batchMutations: {
    ...resolveJoin('created_by', { as: 'name' }),
  },

  roles: { view: 'view_messagetemplates', manage: 'manage_messagetemplates' },
};
