// Auto-generated by db-cli.js — BACKEND schema (trimmed).
// This is the data-shape-only counterpart to the frontend schema.js at the
// matching app/ path. It intentionally does NOT include showInList,
// profileActions, apiBase, rowLinks, customBlocks, sections, moduleRole,
// filters, or actions — those are UI concerns and live in the frontend
// schema only. Edit fields/batchMutations/roles here; edit everything else
// there. Keep the `fields` array in sync between the two by regenerating
// both together (this tool writes both from the same column read).

export const CompaniesSchema = {
  entity: 'crm_companies',

  moduleRole: 'view_crm_companies',

  fields: [
    // key: DB column name | label: display label (unused server-side, kept
    // for parity with the frontend fields) | type: drives SQL/validation
    { key: 'primkey', label: 'Primkey', type: 'number', system: true, editable: false },
    { key: 'record_id', label: 'Record Id', type: 'text', system: true, editable: false },
    { key: 'company_name', label: 'Company Name', type: 'text', title: true, required: true, searchable: true },
    { key: 'industry', label: 'Industry', type: 'text', searchable: true },
    { key: 'company_email', label: 'Company Email', type: 'text', searchable: true },
    { key: 'company_phone', label: 'Company Phone', type: 'text', searchable: true },
    { key: 'website', label: 'Website', type: 'text', searchable: true },
    { key: 'kra_pin', label: 'Kra Pin', type: 'text', searchable: true },
    { key: 'tax_number', label: 'Tax Number', type: 'text', searchable: true },
    { key: 'country', label: 'Country', type: 'groupedSelect', endpoint: '/api/supererpv5/companies', groupByField: 'country', searchable: true },
    { key: 'city', label: 'City', type: 'text', searchable: true },
    { key: 'address', label: 'Address', type: 'textarea', colSpan: 3, searchable: true },
    { key: 'company_logo', label: 'Company Logo', type: 'image' },
    { key: 'company_size', label: 'Company Size', type: 'text', searchable: true },
    { key: 'annual_revenue', label: 'Annual Revenue', type: 'money' },
    { key: 'notes', label: 'Notes', type: 'textarea', colSpan: 3, searchable: true },
    { key: 'assigned_user_id', label: 'Assigned User Id', type: 'text', searchable: true },
    { key: 'created_by', label: 'Created By', type: 'text', searchable: true },
    { key: 'date_created', label: 'Date Created', type: 'datetime' },
    { key: 'date_updated', label: 'Date Updated', type: 'datetime' },
    { key: 'hive_site_id', label: 'Hive Site Id', type: 'text', searchable: true },
    { key: 'hive_site_name', label: 'Hive Site Name', type: 'text', title: true, required: true, searchable: true },
    { key: 'row_count', label: '#', type: 'number', computed: true, editable: false },
  ],

  // Optional: joins enriching each row with data from another table.
  // Same shape as your existing *BatchMutations.js files.
  batchMutations: {
    // "company_name": {
    //   type: "join", table: "companies", link: "company_id:record_id",
    //   select: { "company_name": "company_name" }
    // },
  },

  roles: { view: 'view_companies', manage: 'manage_companies' },
};
