// This is the ONLY file that changes when you clone this module.
// See SCHEMA-SPEC.md for the full reference — quick version below.
// Rough cut auto-generated by db-cli.js (rule-based column-name matching,
// no AI) — hand-tune sections/profileActions/groupedSelect below same as
// any other cloned module.

export const SystemrolesSchema = {
  entity: 'system_roles',              // DB table name; also drives default role names
                                     // (view_systemroles / manage_systemroles) and apiBase
  label: 'Systemroles',                 // optional, defaults to entity capitalized
  apiBase: '/api/assetguard/systemroles',

  // Page-level UI gate — checked once, for the WHOLE grid AND the WHOLE
  // profile/form page, via mosyACTRLHasRole. No moduleRole set -> open to
  // anyone (same additive convention as every other role/flag in this
  // file). This is a different layer than the per-action `role` flag
  // inside individual moduleActions entries below: moduleRole controls
  // whether someone can reach the page at all; a per-action role controls
  // whether one specific button shows up once they're already in. Same
  // UI-only caveat as those: route.js needs the equivalent server-side
  // check for this to be real enforcement, not just hiding.
  moduleRole: 'view_systemroles',

  // Field keys shown as columns in list view, in display order.
  showInList: ['row_count', 'role_name', 'permission_count', 'user_count'],

  rowLinks: [],

  // profileActions — one array, three possible places each entry can
  // render, spelled out explicitly on every entry (no implicit
  // defaults): the grid, DynamicForm.jsx, and EntityRowOptions' dropdown
  // all read this SAME array, each filtering on its own flag. Comment an
  // entry out, or flip a flag to false, and it disappears from that one
  // place — no component edit needed.
  //   grid: true/false      -> grid toolbar (list page)
  //   form: true/false      -> profile/form toolbar ('save' is also the
  //                            primary submit button — DynamicForm picks
  //                            the submit button as whichever entry has
  //                            both form:true and key:'save')
  //   rowAction: true/false -> per-row dropdown in the grid (EntityRowOptions)
  //   editOnly: true        -> only shown once a record exists (form/rowAction contexts)
  //   role: 'role_name'     -> UI-ONLY gate, checked via mosyACTRLHasRole
  //                            (session roles from localStorage). Omit
  //                            entirely and the action is open to anyone —
  //                            this is additive, not a default-deny system.
  //                            NOTE: this does not by itself stop the
  //                            request server-side — route.js currently
  //                            gates every mutation behind one blanket
  //                            manage_<entity> role regardless of which
  //                            action triggered it. Real enforcement needs
  //                            the same per-action role checked there too.
  profileActions: [
    { key: 'back', label: 'Back to list', icon: 'arrow-left', variant: 'outline-secondary', navigateTo: '/assetguard/systemroles/list', grid: false, form: true },
    { key: 'save', label: 'Save', icon: 'save', variant: 'primary', grid: false, form: true, rowAction: false },
    { key: 'delete', label: 'Delete', icon: 'trash', variant: 'outline-danger', confirm: 'Are you sure you want to delete this systemrole?', editOnly: true, grid: false, form: true, rowAction: true, role: 'manage_systemroles' },
    { key: 'view', label: 'View more', icon: 'edit', rowAction: true },
    //{ key: 'new', label: 'Add role', icon: 'plus', variant: 'outline-primary', navigateTo: '/assetguard/systemroles/profile', grid: true, form: false, rowAction: false },
    { key: 'clone', label: 'Clone and edit', icon: 'copy', variant: 'outline-secondary', editOnly: true, grid: false, form: true, rowAction: false, role: 'manage_systemroles' },
    { key: 'add_new_role', label: 'Add Role', type: 'action', icon: 'plus-circle', variant:"primary", grid: true, form: false, rowAction: false },
    { key: 'view_modules', label: 'Modules', icon: 'list', navigateTo: '/assetguard/systemmodules/list', grid: true, form: false, rowAction: false },
    { key: 'view_matrix', label: 'Access control', icon: 'shield', navigateTo: '/assetguard/accessmatrix', grid: true, form: false, rowAction: false },
    { key: 'view_role_permissions', type: 'action', editOnly: true, label: 'Permissions', icon: 'list', grid: false, form: true, rowAction: true },
    { key: 'view_users_with_roles', type: 'action', editOnly: true, label: 'View Users', icon: 'users', grid: false, form: true, rowAction: true },
    
    //{ key: 'filterByDate', label: 'Filter by date', icon: 'calendar', variant: 'outline-primary', type: 'action', grid: true, form: false, rowAction: false },
  ],

  // customBlocks — the escape hatch for UI that doesn't fit the rigid
  // field-grid: a raw component, handed the SAME values/setValue/errors/
  // schema/isEditing/row context a real field gets. A block's `key` just
  // sits in a section's `fields` array exactly like a real field key —
  // wherever it appears there is where it renders. Empty by default;
  // uncomment and point at a real component when a field needs custom UI
  // (see SCHEMA-SPEC.md for the full pattern, e.g. companies/schema.js).
  customBlocks: [
    // { key: 'some_field', component: SomeComponent, colSpan: 7 },
  ],

  fieldGroups: [],

  sections: [
    { key: 'basic_information', label: 'Basic Information', columns: 1, fields: ['role_name', 'role_description','date_created'] },
  ],

  fields: [
    // key: DB column name | label: shown on screen | type: drives input + SQL type
    { key: 'primkey', label: 'Primkey', type: 'number', system: true, editable: false },
    { key: 'record_id', label: 'Record Id', type: 'text', system: true, editable: false },
    { key: 'role_name', label: 'Role Name', type: 'text', title: true, required: true, searchable: true },
    { key: 'role_description', label: 'Role Description', type: 'text', searchable: true },
    { key: 'permission_name', label: 'Module', type: 'text', searchable: true },
    { key: 'permission_count', label: 'Permissions', type: 'text', computed: true, editable: false },
    { key: 'permissions', label: 'Permissions',
      type: 'liveSearch', colSpan: 6,
      endpoint: '/api/assetguard/systemmodules',
      searchTable: 'system_modules',
      valueField: 'record_id',      // id column on system_modules
      displayField: 'module_name',  // label column on system_modules — what search results/defaultValue text actually render
      labelKey: 'permission_name',  // cached label already joined onto THIS row (system_roles) — only used to seed defaultValue on load
    },
    { key: 'user_count', label: 'Users', type: 'number', sum: true, searchable: true },
    { key: 'date_created', label: 'Date Created', type: 'datetime', computed: true, editable: false },
    { key: 'row_count', label: '#', type: 'number', computed: true, editable: false },
    // more fields... see SCHEMA-SPEC.md for the full field option list
    // (searchable, editable, options, priority, db overrides)
  ],

  filters: [
    { key: 'all', label: 'All', query: {} },
  ],

  actions: [
    // { key: 'some_action', label: 'Do Something', appliesTo: { status: 'x' } },
    // "key" must match a function registered in lib/actionsRegistry.js
  ],

  // Optional: joins enriching each row with data from another table.
  // Same shape as your existing *BatchMutations.js files.
  batchMutations: {
    // "_staff_full_name_staff_id": {
    //   type: "join", table: "staff", link: "staff_id:record_id",
    //   select: { "_staff_full_name_staff_id": "full_name" }
    // },
  },

  // Optional: only needed if permission keys don't follow the
  // view_<entity> / manage_<entity> default.
  // roles: { view: 'view_systemroles', manage: 'manage_systemroles' },
};
