// Auto-generated by db-cli.js — BACKEND schema (trimmed).
// This is the data-shape-only counterpart to the frontend schema.js at the
// matching app/ path. It intentionally does NOT include showInList,
// profileActions, apiBase, rowLinks, customBlocks, sections, moduleRole,
// filters, or actions — those are UI concerns and live in the frontend
// schema only. Field entries also omit `label` here (UI-only display
// text) even though the frontend fields carry it. Edit
// fields/batchMutations/roles here; edit everything else there. Keep the
// `fields` array in sync between the two by regenerating both together
// (this tool writes both from the same column read).

import { resolveJoin } from '../../imsv2Schema';

export const PaymentrequestsSchema = {
  entity: 'smart_payment_requests',

  moduleRole: 'view_smart_payment_requests',

  fields: [
    // key: DB column name | type: drives SQL/validation (label omitted —
    // UI-only, lives in the frontend schema)
    { key: 'primkey', type: 'number', system: true, editable: false },
    { key: 'record_id', type: 'text', system: true, editable: false },
    { key: 'request_reference', type: 'text', searchable: true },
    { key: 'request_title', type: 'text', searchable: true },
    { key: 'related_module', type: 'text', searchable: true },
    { key: 'related_record_id', type: 'text', searchable: true },
    { key: 'payer_name', type: 'text', title: true, searchable: true },
    { key: 'payer_phone', type: 'text', searchable: true },
    { key: 'payer_email', type: 'text', searchable: true },
    { key: 'amount_requested', type: 'money' },
    { key: 'amount_paid', type: 'money' },
    { key: 'balance_amount', type: 'money' },
    { key: 'payment_shortcode', type: 'text', searchable: true },
    { key: 'payment_link', type: 'text', searchable: true },
    { key: 'request_notes', type: 'textarea', colSpan: 3, searchable: true },
    { key: 'expiry_date', type: 'datetime' },
    { key: 'request_status', type: 'text', searchable: true },
    { key: 'created_by', type: 'text', searchable: true },
    { key: 'created_on', type: 'datetime' },
    { key: 'updated_on', type: 'datetime' },
    { key: 'hive_site_id', type: 'text', searchable: true },
    { key: 'hive_site_name', type: 'text', title: true, searchable: true },
    { key: 'row_count', type: 'number', computed: true, editable: false },
  ],

  // Optional: joins enriching each row with data from another table.
  // Same shape as your existing *BatchMutations.js files.
  batchMutations: {
    ...resolveJoin('created_by', { as: 'name' }),
  },

  roles: { view: 'view_paymentrequests', manage: 'manage_paymentrequests' },
};
