// This is the ONLY file that changes when you clone this module.
// See SCHEMA-SPEC.md for the full reference — quick version below.
// Rough cut auto-generated by db-cli.js (rule-based column-name matching,
// no AI) — hand-tune sections/profileActions/groupedSelect below same as
// any other cloned module.
//
// FRONTEND schema — full UI shape (showInList, profileActions, apiBase,
// rowLinks, customBlocks, sections, moduleRole, etc). The trimmed backend
// counterpart lives alongside this at the api/ path and only carries
// entity/fields/batchMutations/roles.

const moduleApi =  '/api/supererpv5/revenueplan';

export const RevenueplanSchema = {
  entity: 'expected_revenue',              // DB table name; also drives default role names
                                     // (view_revenueplan / manage_revenueplan) and apiBase
  label: 'Revenueplan',                 // optional, defaults to entity capitalized
  apiBase: moduleApi,

  //api endpint for importing data from csv
  importDataEndpoint : '/api/supererpv5/revenueplan/import',

  // Page-level UI gate — checked once, for the WHOLE grid AND the WHOLE
  // profile/form page, via mosyACTRLHasRole. No moduleRole set -> open to
  // anyone (same additive convention as every other role/flag in this
  // file). This is a different layer than the per-action `role` flag
  // inside individual moduleActions entries below: moduleRole controls
  // whether someone can reach the page at all; a per-action role controls
  // whether one specific button shows up once they're already in. Same
  // UI-only caveat as those: route.js needs the equivalent server-side
  // check for this to be real enforcement, not just hiding.
  moduleRole: 'view_revenueplan',

  // Field keys shown as columns in list view, in display order.
  showInList: ['row_count', 'revenue_month', 'client_id', 'deal_id', 'expected_amount', 'currency_code', 'payment_status', 'payment_ref_no'],

  //export columns these columns are used to generate upload csv template file
  exportColumns: ['row_count', 'revenue_month', 'client_id', 'deal_id', 'expected_amount', 'currency_code', 'payment_status', 'payment_ref_no'],

  gridOptions : {
   checkBoxes : false,
   checkFunction : "gridCheckBoxAction"  
  },

  multiGridRows: [
    // {
    //   key: 'payment_details',
    //   parentTable: 'gps_logs',
    //   title: 'Log summary',
    //   columns: [
    //     { key: 'speed', label: 'Speed' },
    //     { key: 'latitude', label: 'Lat' },
    //     { key: 'longitude', label: 'Long' , sum: true},
    //     { key: 'remark', label: 'Selling price' }
    //   ],
    //   viewMoreLink: '../gpslogs/list',
    //   filter: { order_id: '{record_id}' },
    // },
  ],

  rowLinks: [],

  // profileActions — one array, three possible places each entry can
  // render, spelled out explicitly on every entry (no implicit
  // defaults): the grid, DynamicForm.jsx, and EntityRowOptions' dropdown
  // all read this SAME array, each filtering on its own flag. Comment an
  // entry out, or flip a flag to false, and it disappears from that one
  // place — no component edit needed.
  //   grid: true/false      -> grid toolbar (list page)
  //   form: true/false      -> profile/form toolbar ('save' is also the
  //                            primary submit button — DynamicForm picks
  //                            the submit button as whichever entry has
  //                            both form:true and key:'save')
  //   rowAction: true/false -> per-row dropdown in the grid (EntityRowOptions)
  //   editOnly: true        -> only shown once a record exists (form/rowAction contexts)
  //   role: 'role_name'     -> UI-ONLY gate, checked via mosyACTRLHasRole
  //                            (session roles from localStorage). Omit
  //                            entirely and the action is open to anyone —
  //                            this is additive, not a default-deny system.
  //                            NOTE: this does not by itself stop the
  //                            request server-side — route.js currently
  //                            gates every mutation behind one blanket
  //                            manage_<entity> role regardless of which
  //                            action triggered it. Real enforcement needs
  //                            the same per-action role checked there too.
  profileActions: [
    { key: 'back', label: 'Back to list', icon: 'arrow-left', variant: 'outline-secondary', navigateTo: '/supererpv5/revenueplan/list', grid: false, form: true },
    { key: 'save', label: 'Save', icon: 'save', variant: 'primary', grid: false, form: true, rowAction: false },
    { key: 'delete', label: 'Delete', icon: 'trash', variant: 'outline-danger', confirm: 'Are you sure you want to delete this revenueplan?', editOnly: true, grid: false, form: true, rowAction: true, role: 'manage_revenueplan' },
    { key: 'view', label: 'View more', icon: 'edit', rowAction: true },
    { key: 'filter_by_month', label: 'Filter by month', icon: 'calendar',  colorClass:"bg-success text-white", grid:true, type: 'action', form: false, rowAction: false },
    { key: 'filter_by_status', label: 'Filter by status', icon: 'bolt', colorClass:"bg-light", grid:true, type: 'action', form: false, rowAction: false },
    { key: 'mark_paid', label: 'Update status', icon: 'info-circle', grid:false, type: 'action', form: true, rowAction: true },
    { key: 'filter_by_client', label: 'Filter by account', icon: 'user', grid:true, type: 'action', form: false, rowAction: false },
    
    { key: 'new', label: 'New Revenueplan', icon: 'plus', variant: 'outline-primary', navigateTo: '/supererpv5/revenueplan/profile', grid: true, form: false, rowAction: false },
    //{ key: 'clone', label: 'Clone Record', icon: 'copy', variant: 'outline-secondary', editOnly: true, grid: false, form: true, rowAction: false, role: 'manage_revenueplan' },
    //{ key: 'filterByDate', label: 'Filter by date', icon: 'calendar', variant: 'outline-primary', type: 'action', grid: true, form: false, rowAction: false },
  ],

  // customBlocks — the escape hatch for UI that doesn't fit the rigid
  // field-grid: a raw component, handed the SAME values/setValue/errors/
  // schema/isEditing/row context a real field gets. A block's `key` just
  // sits in a section's `fields` array exactly like a real field key —
  // wherever it appears there is where it renders. Empty by default;
  // uncomment and point at a real component when a field needs custom UI
  // (see SCHEMA-SPEC.md for the full pattern, e.g. companies/schema.js).
  customBlocks: [
    // { key: 'some_field', component: SomeComponent, colSpan: 7 },
  ],

  fieldGroups: [],

  sections: [
    { key: 'basic_information', label: 'Basic Information', columns: 3, fields: ['revenue_month', 'client_id', 'deal_id', 'expected_amount', 'currency_code', 'payment_status', 'payment_ref_no'] },
    { key: 'other_details', label: 'Other Details', columns: 3, fields: ['expected_close_date', 'probability_percent', 'revenue_source_type', 'revenue_title', 'invoice_id', 'lead_id', 'revenue_status', 'revenue_description', 'assigned_to', 'hive_site_id', 'hive_site_name'] },
  ],

  fields: [
    // key: DB column name | label: shown on screen | type: drives input + SQL type
    { key: 'primkey', label: 'Primkey', type: 'number', system: true, editable: false },
    { key: 'record_id', label: 'Record Id', type: 'text', system: true, editable: false },
    { key: 'revenue_month', label: 'Revenue Month', type: 'groupedSelect', endpoint:moduleApi },
    { key: 'client_id', label: 'Client Id', type: 'text', searchable: true },
    { key: 'deal_id', label: 'Deal Id', type: 'text', searchable: true },
    { key: 'expected_amount', label: 'Expected Amount', type: 'money' , sum:true},
    { key: 'currency_code', label: 'Currency Code', type: 'text', title: true, searchable: true },
    { key: 'payment_status', label: 'Payment Status', type: 'select', options:['Paid', 'Unpaid'], searchable: true },
    { key: 'payment_ref_no', label: 'Payment Ref No', type: 'text', searchable: true },
    { key: 'expected_close_date', label: 'Expected Close Date', type: 'datetime' },
    { key: 'probability_percent', label: 'Probability Percent', type: 'text', searchable: true },
    { key: 'revenue_source_type', label: 'Revenue Source Type', type: 'text', searchable: true },
    { key: 'revenue_title', label: 'Revenue Title', type: 'text', searchable: true },
    { key: 'invoice_id', label: 'Invoice Id', type: 'text', searchable: true },
    { key: 'lead_id', label: 'Lead Id', type: 'text', searchable: true },
    { key: 'revenue_status', label: 'Revenue Status', type: 'text', searchable: true },
    { key: 'revenue_description', label: 'Revenue Description', type: 'textarea', colSpan: 3, searchable: true },
    { key: 'assigned_to', label: 'Assigned To', type: 'text', searchable: true },
    { key: 'hive_site_id', label: 'Hive Site Id', type: 'text', searchable: true },
    { key: 'hive_site_name', label: 'Hive Site Name', type: 'text', title: true, searchable: true },
    { key: 'row_count', label: '#', type: 'number', computed: true, editable: false },
    //  live search field sample 
    // { key: 'permissions', label: 'Permissions',
    //   type: 'liveSearch', colSpan: 6,
    //   endpoint: '/api/assetguard/systemmodules',
    //   searchTable: 'system_modules',
    //   valueField: 'record_id',      // id column on system_modules
    //   displayField: 'module_name',  // label column on system_modules — what search results/defaultValue text actually render
    //   labelKey: 'permission_name',  // cached label already joined onto THIS row (system_roles) — only used to seed defaultValue on load
    // },
    // more fields... see SCHEMA-SPEC.md for the full field option list
    // (searchable, editable, options, priority, db overrides)
  ],

  filters: [
    { key: 'all', label: 'All', query: {} },
  ],

  actions: [
    // { key: 'some_action', label: 'Do Something', appliesTo: { status: 'x' } },
    // "key" must match a function registered in lib/actionsRegistry.js
  ],

 

  // Optional: only needed if permission keys don't follow the
  // view_<entity> / manage_<entity> default.
  // roles: { view: 'view_revenueplan', manage: 'manage_revenueplan' },
};
