// imsv2Schema.js
// -------------------------------------------------------------------
// AUTO-GENERATED by schemamap.js from app\imsv2\schemamap.txt — do not hand-edit
// the globalRelations object below. Edit the spec file and rerun:
//   node schemamap.js
//
// Column name on a specific module differs from the relation key (e.g.
// a polymorphic "__" key, or a renamed FK column) — pass 'key' in
// overrides so both sides stay in sync.
// Override ANYTHING else per-module the same way — second arg always
// wins, shallow merge over the global default.
// Unknown relation key throws instead of silently returning undefined
// (fail loud, not silent).
//
// endpoint (frontend only) resolves live via apiRoutes.json/getApiRoutes,
// keyed by table.replace(/_/g, '') — the SAME default routeKey db-cli.js
// writes when it builds that table's own schema.js. If that table's
// schema was built with a custom --list-name prefix, its real
// apiRoutes.json key won't match this guess — hand-fix that one entry's
// endpoint here (or re-point it at a literal string) rather than
// regenerating; schemamap.js has no way to know about a prefix chosen in
// a different tool's run.
// -------------------------------------------------------------------

export const globalRelations = {

  bundle_id: {
    table: "system_role_bundles",
    valueField: "bundle_id",
    displayField: "bundle_name",
    cacheField: "bundle_name",
    label: "Bundle",
    // used by: user_bundle_role_functions
  },

  client_id: {
    table: "contacts",
    valueField: "contact_id",
    displayField: "contact_name",
    cacheField: "contact_name",
    label: "Contact",
    // used by: expected_revenue
  },

  contact_id: {
    table: "contacts",
    valueField: "contact_id",
    displayField: "contact_name",
    cacheField: "contact_name",
    label: "Contact",
    // used by: activities, ledger, notes_ideas, opportunities
  },

  created_by: {
    table: "system_users",
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: activities, notes_ideas, expected_revenue
  },

  deal_id: {
    table: "opportunities",
    valueField: "opportunity_id",
    displayField: "title",
    cacheField: "title",
    label: "Opportunity",
    // used by: expected_revenue
  },

  module_id: {
    table: "system_modules",
    valueField: "record_id",
    displayField: "module_name",
    cacheField: "module_name",
    label: "Module",
    // used by: system_role_permissions
  },

  opportunity_id: {
    table: "opportunities",
    valueField: "opportunity_id",
    displayField: "title",
    cacheField: "title",
    label: "Opportunity",
    // used by: activities, ledger, notes_ideas
  },

  role_id: {
    table: "system_roles",
    valueField: "record_id",
    displayField: "role_name",
    cacheField: "role_name",
    label: "Role",
    // used by: system_role_permissions, user_bundle_role_functions, user_manifest_
  },

  user_id: {
    table: "system_users",
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: user_manifest_
  },

  user_role: {
    table: "system_roles",
    valueField: "role_name",
    displayField: "role_name",
    cacheField: "role_name",
    label: "Role",
    // used by: system_users
  },

};

function cacheKeyFor(rel, columnKey) {
  return `_${rel.table}_${rel.cacheField}_${columnKey}`;
}

function getRelation(relationKey, fnName) {
  const rel = globalRelations[relationKey];
  if (!rel) {
    throw new Error(
      `${fnName}: no globalRelations entry for "${relationKey}". ` +
      `Regenerate from schemamap.txt, or define this field/join locally instead.`
    );
  }
  return rel;
}

// Use it on the BACKEND schema (in 'batchMutations:'):
//     ...resolveJoin('staff_id')
//     ...resolveJoin('related_record_id__app_users', { key: 'related_record_id' })
//
// Cache alias too long/ugly (e.g. "_fuel_stations_station_name_fuel_station_id")?
// Override it with 'as' — pass the SAME 'as' value to resolveField on the
// frontend side so the two stay pointed at the same column on the row:
//     ...resolveJoin('fuel_station_id', { as: 'station_name' })
export function resolveJoin(relationKey, overrides = {}) {
  const rel = getRelation(relationKey, 'resolveJoin');
  const columnKey = overrides.key || relationKey;
  const cacheKey = overrides.as || cacheKeyFor(rel, columnKey);
  const descriptor = {
    type: 'join',
    table: rel.table,
    link: `${columnKey}:${rel.valueField}`,
    select: { [cacheKey]: rel.cacheField },
  };
  const { key: _unusedKey, as: _unusedAs, ...restOverrides } = overrides;
  return { [cacheKey]: { ...descriptor, ...restOverrides } };
}

// ---------------------------------------------------------------------
// Detected "reverse" relations (record_id referenced FROM another table).
// These are candidate multiGridRows / child-grid wiring, NOT parent
// lookups, so they are not turned into resolveField/resolveJoin entries.
// Wire manually into multiGridRows on the parent module's schema.js.
// ---------------------------------------------------------------------
// (none detected in this spec)
