// Auto-generated by db-cli.js — BACKEND schema (trimmed).
// This is the data-shape-only counterpart to the frontend schema.js at the
// matching app/ path. It intentionally does NOT include showInList,
// profileActions, apiBase, rowLinks, customBlocks, sections, moduleRole,
// filters, or actions — those are UI concerns and live in the frontend
// schema only. Edit fields/batchMutations/roles here; edit everything else
// there. Keep the `fields` array in sync between the two by regenerating
// both together (this tool writes both from the same column read).

export const LeadsSchema = {
  entity: 'crm_leads',

  moduleRole: 'view_crm_leads',

  fields: [
    // key: DB column name | label: display label (unused server-side, kept
    // for parity with the frontend fields) | type: drives SQL/validation
    { key: 'primkey', label: 'Primkey', type: 'number', system: true, editable: false },
    { key: 'record_id', label: 'Record Id', type: 'text', system: true, editable: false },
    { key: 'lead_name', label: 'Lead Name', type: 'text', title: true, required: true, searchable: true },
    { key: 'contact_id', label: 'Contact Id', type: 'text', searchable: true },
    { key: 'company_id', label: 'Company Id', type: 'text', searchable: true },
    { key: 'lead_source', label: 'Lead Source', type: 'text', searchable: true },
    { key: 'lead_status', label: 'Lead Status', type: 'text', searchable: true },
    { key: 'interest_level', label: 'Interest Level', type: 'text', searchable: true },
    { key: 'estimated_value', label: 'Estimated Value', type: 'money' },
    { key: 'assigned_user_id', label: 'Assigned User Id', type: 'text', searchable: true },
    { key: 'next_followup_date', label: 'Next Followup Date', type: 'datetime' },
    { key: 'notes', label: 'Notes', type: 'textarea', colSpan: 3, searchable: true },
    { key: 'converted_status', label: 'Converted Status', type: 'text', searchable: true },
    { key: 'converted_contact_id', label: 'Converted Contact Id', type: 'text', searchable: true },
    { key: 'converted_deal_id', label: 'Converted Deal Id', type: 'text', searchable: true },
    { key: 'created_by', label: 'Created By', type: 'text', searchable: true },
    { key: 'date_created', label: 'Date Created', type: 'datetime' },
    { key: 'date_updated', label: 'Date Updated', type: 'datetime' },
    { key: 'hive_site_id', label: 'Hive Site Id', type: 'text', searchable: true },
    { key: 'hive_site_name', label: 'Hive Site Name', type: 'text', title: true, required: true, searchable: true },
    { key: 'row_count', label: '#', type: 'number', computed: true, editable: false },
  ],

  // Optional: joins enriching each row with data from another table.
  // Same shape as your existing *BatchMutations.js files.
  batchMutations: {
    // "_staff_full_name_staff_id": {
    //   type: "join", table: "staff", link: "staff_id:record_id",
    //   select: { "_staff_full_name_staff_id": "full_name" }
    // },
  },

  roles: { view: 'view_leads', manage: 'manage_leads' },
};
