// Auto-generated by db-cli.js — BACKEND schema (trimmed).
// This is the data-shape-only counterpart to the frontend schema.js at the
// matching app/ path. It intentionally does NOT include showInList,
// profileActions, apiBase, rowLinks, customBlocks, sections, moduleRole,
// filters, or actions — those are UI concerns and live in the frontend
// schema only. Edit fields/batchMutations/roles here; edit everything else
// there. Keep the `fields` array in sync between the two by regenerating
// both together (this tool writes both from the same column read).

export const RevenueplanSchema = {
  entity: 'expected_revenue',

  moduleRole: 'view_expected_revenue',

  fields: [
    // key: DB column name | label: display label (unused server-side, kept
    // for parity with the frontend fields) | type: drives SQL/validation
    { key: 'primkey', label: 'Primkey', type: 'number', system: true, editable: false },
    { key: 'record_id', label: 'Record Id', type: 'text', system: true, editable: false },
    { key: 'revenue_month', label: 'Revenue Month', type: 'text', searchable: true },
    { key: 'client_id', label: 'Client Id', type: 'text', searchable: true },
    { key: 'deal_id', label: 'Deal Id', type: 'text', searchable: true },
    { key: 'expected_amount', label: 'Expected Amount', type: 'money' },
    { key: 'currency_code', label: 'Currency Code', type: 'text', title: true, searchable: true },
    { key: 'payment_status', label: 'Payment Status', type: 'text', searchable: true },
    { key: 'payment_ref_no', label: 'Payment Ref No', type: 'text', searchable: true },
    { key: 'expected_close_date', label: 'Expected Close Date', type: 'datetime' },
    { key: 'probability_percent', label: 'Probability Percent', type: 'text', searchable: true },
    { key: 'revenue_source_type', label: 'Revenue Source Type', type: 'text', searchable: true },
    { key: 'revenue_title', label: 'Revenue Title', type: 'text', searchable: true },
    { key: 'invoice_id', label: 'Invoice Id', type: 'text', searchable: true },
    { key: 'lead_id', label: 'Lead Id', type: 'text', searchable: true },
    { key: 'revenue_status', label: 'Revenue Status', type: 'text', searchable: true },
    { key: 'revenue_description', label: 'Revenue Description', type: 'textarea', colSpan: 3, searchable: true },
    { key: 'assigned_to', label: 'Assigned To', type: 'text', searchable: true },
    { key: 'hive_site_id', label: 'Hive Site Id', type: 'text', searchable: true },
    { key: 'hive_site_name', label: 'Hive Site Name', type: 'text', title: true, searchable: true },
    { key: 'row_count', label: '#', type: 'number', computed: true, editable: false },
  ],

  // Optional: joins enriching each row with data from another table.
  // Same shape as your existing *BatchMutations.js files.
  batchMutations: {
    // "_staff_full_name_staff_id": {
    //   type: "join", table: "staff", link: "staff_id:record_id",
    //   select: { "_staff_full_name_staff_id": "full_name" }
    // },
  },

  roles: { view: 'view_revenueplan', manage: 'manage_revenueplan' },
};
