// This is the ONLY file that changes when you clone this module.
// See SCHEMA-SPEC.md for the full reference — quick version below.
// Rough cut auto-generated by db-cli.js (rule-based column-name matching,
// no AI) — hand-tune sections/profileActions/groupedSelect below same as
// any other cloned module.
//
// FRONTEND schema — full UI shape (showInList, profileActions, apiBase,
// rowLinks, customBlocks, sections, moduleRole, etc). The trimmed backend
// counterpart lives alongside this at the api/ path and only carries
// entity/fields/batchMutations/roles.

import { getApiRoutes } from '../AppRoutes/apiRoutesHandler';
// Use default base root (/)
const apiRoutes = getApiRoutes();
const moduleApi = apiRoutes.mosyreminders.base;

export const MosyremindersSchema = {
  entity: 'mosy_reminders',              // DB table name; also drives default role names
                                     // (view_mosyreminders / manage_mosyreminders) and apiBase
  label: 'System Reminders',                 // optional, defaults to entity capitalized
  apiBase: moduleApi,

  //api endpint for importing data from csv
  importDataEndpoint : apiRoutes.mosyreminders.import,

  // Page-level UI gate — checked once, for the WHOLE grid AND the WHOLE
  // profile/form page, via mosyACTRLHasRole. No moduleRole set -> open to
  // anyone (same additive convention as every other role/flag in this
  // file). This is a different layer than the per-action `role` flag
  // inside individual moduleActions entries below: moduleRole controls
  // whether someone can reach the page at all; a per-action role controls
  // whether one specific button shows up once they're already in. Same
  // UI-only caveat as those: route.js needs the equivalent server-side
  // check for this to be real enforcement, not just hiding.
  moduleRole: 'view_mosyreminders',


  gridOptions : {
   checkBoxes : false,
   checkFunction : "gridCheckBoxAction"  
  },

  multiGridRows: [
    // {
    //   key: 'order_items',
    //   parentTable: 'gps_logs',
    //   title: 'Log summary',
    //   columns: [
    //     { key: 'speed', label: 'Speed' },
    //     { key: 'latitude', label: 'Lat' },
    //     { key: 'longitude', label: 'Long' , sum: true},
    //     { key: 'remark', label: 'Selling price' }
    //   ],
    //   viewMoreLink: '../gpslogs/list',
    //   filter: { order_id: '{record_id}' },
    // },
  ],

  rowLinks: [],

  // Actions available from the list view, form and grid in display order.
  //{ 
  // key: 'filter_by_client', -- name of the action 
  // label: 'Filter by account', -- button label 
  // icon: 'user', -- icon of the buttons
  // grid:true, -- show on grid or not, 
  // type: 'action', -- indicates action on form registry 
  // form: false, -- show on form or not, 
  // rowAction: false --show on row drop down or not
  // variant : 'outline-primary', -- button color  variant
  // navigateTo: '/supererpv5/revenueplan/profile', -- route to navigate to -  for link buttons only 
  // colorClass:"bg-success text-white", -- button color classname 
  // confirm: 'Are you sure you want to delete this revenueplan?', -- confirmation message for delete button
  // editOnly: true, -- show on edit only or not
  // role: 'manage_revenueplan' -- role required for this action
  //},

  profileActions: [
    { key: 'back', label: 'Back to list', icon: 'arrow-left', variant: 'outline-secondary', navigateTo: '/imsv2/mosyreminders/list', grid: false, form: true },
    { key: 'save', label: 'Save', icon: 'save', variant: 'primary', grid: false, form: true, rowAction: false },
    { key: 'delete', label: 'Delete', icon: 'trash', variant: 'outline-danger', confirm: 'Are you sure you want to delete this mosyreminder?', editOnly: true, grid: false, form: true, rowAction: true, role: 'manage_mosyreminders' },
    { key: 'view', label: 'View more', icon: 'edit', rowAction: true },
    // Routes through logicControl/actionsRegistry.js -> MosySendSmartReminder
    // instead of navigating to the plain profile form.
    { key: 'new', label: 'New Reminder', icon: 'plus', variant: 'outline-primary', type: 'action', grid: true, form: false, rowAction: false },
    { key: 'clone', label: 'Clone Record', icon: 'copy', variant: 'outline-secondary', editOnly: true, grid: false, form: true, rowAction: false, role: 'manage_mosyreminders' },
    //{ key: 'filterByDate', label: 'Filter by date', icon: 'calendar', variant: 'outline-primary', type: 'action', grid: true, form: false, rowAction: false },

    // Opens the same composer pre-filled with this row's data, saved via PUT.
    { key: 'edit_reminder', label: 'Edit', icon: 'edit', variant: 'outline-primary', type: 'action', grid: false, form: false, rowAction: true },
    // Flips status Active <-> Inactive in place, no modal.
    { key: 'toggle_status', label: 'Activate / Deactivate', icon: 'power-off', variant: 'outline-secondary', type: 'action', grid: false, form: false, rowAction: true },
  ],



  // customBlocks — the escape hatch for UI that doesn't fit the rigid
  // field-grid: a raw component, handed the SAME values/setValue/errors/
  // schema/isEditing/row context a real field gets. A block's `key` just
  // sits in a section's `fields` array exactly like a real field key —
  // wherever it appears there is where it renders. Empty by default;
  // uncomment and point at a real component when a field needs custom UI
  // (see SCHEMA-SPEC.md for the full pattern, e.g. companies/schema.js).
  customBlocks: [
    // { key: 'some_field', component: SomeComponent, colSpan: 7 },
  ],

  fieldGroups: [],
  // Field keys shown as columns in list view, in display order.
  showInList: ['row_count', 'status','last_sent_date', 'time_of_day', 'days_of_week', 'recipients_phone', 'recipients_email', 'subject', 'message'],

  //export columns these columns are used to generate upload csv template file
  exportColumns: ['last_sent_date', 'time_of_day', 'days_of_week', 'recipients_phone', 'recipients_email', 'subject', 'message'],

  sections: [
    { key: 'basic_information', label: 'Basic Information', columns: 3, fields: ['app_name', 'time_of_day', 'days_of_week', 'repeat_type', 'subject', 'recipients_phone', 'recipients_email', 'message'] },
    { key: 'other_details', label: 'Other Details', columns: 3, fields: ['variable_source', 'status', 'related_record_id', 'last_sent_date', 'reg_date'] },
  ],

  fields: [
    // key: DB column name | label: shown on screen | type: drives input + SQL type
    { key: 'primkey', label: 'Primkey', type: 'number', system: true, editable: false },
    { key: 'reminder_id', label: 'Reminder Id', type: 'text', system: true, editable: false },
    // Kept out of `sections` (not shown on the form) but must stay in
    // `fields` — the DB column is NOT NULL with no default, and only
    // fields listed here end up in the submitted values object at all.
    { key: 'tenant_id', label: 'Tenant Id', type: 'text', system: true, editable: false },
    { key: 'app_name', label: 'App Name', type: 'text', title: true, required: true, colSpan: 4 },
    { key: 'time_of_day', label: 'Time Of Day', type: 'text', colSpan: 4 },
    { key: 'days_of_week', label: 'Days Of Week', type: 'text', colSpan: 4 },
    { key: 'repeat_type', label: 'Frequency', type: 'select', options: ['repeat', 'once'], colSpan: 4 },
    { key: 'subject', label: 'Subject', type: 'text', colSpan: 4 , title:true },
    { key: 'recipients_phone', label: 'Recipients Phone', type: 'textarea', colSpan: 12 },
    { key: 'recipients_email', label: 'Recipients Email', type: 'textarea', colSpan: 12 },
    { key: 'message', label: 'Message', type: 'textarea', colSpan: 12 },
    { key: 'variable_source', label: 'Variable Source', type: 'text', colSpan: 4 },
    { key: 'status', label: 'Status', type: 'groupedSelect', endpoint: moduleApi, groupByField: 'status', colSpan: 4 },
    // Loose pointer at whichever module created this reminder (contact_id,
    // activity_id, etc) — set only via MosySmartReminder, not hand-edited.
    // Filter another module's reminder list with fixedQuery={{ relatedRecordId: btoa(row.record_id) }}.
    { key: 'related_record_id', label: 'Related Record Id', type: 'text', editable: false, colSpan: 4 },
    { key: 'last_sent_date', label: 'Last Sent Date', type: 'datetime', editable: false, colSpan: 4 },
    { key: 'reg_date', label: 'Reg Date', type: 'datetime', editable: false, colSpan: 4 },
    { key: 'row_count', label: '#', type: 'number', computed: true, editable: false },
    //  live search field sample 
    // { key: 'permissions', label: 'Permissions',
    //   type: 'liveSearch', colSpan: 6,
    //   endpoint: '/api/assetguard/systemmodules',
    //   searchTable: 'system_modules',
    //   valueField: 'record_id',      // id column on system_modules
    //   displayField: 'module_name',  // label column on system_modules — what search results/defaultValue text actually render
    //   labelKey: 'permission_name',  // cached label already joined onto THIS row (system_roles) — only used to seed defaultValue on load
    // },
    // more fields... see SCHEMA-SPEC.md for the full field option list
    // (searchable, editable, options, priority, db overrides)
  ],

  filters: [
    { key: 'all', label: 'All', query: {} },
  ],

  actions: [
    // { key: 'some_action', label: 'Do Something', appliesTo: { status: 'x' } },
    // "key" must match a function registered in lib/actionsRegistry.js
  ],

// for button color classes  
// dyn-btn-accent-amber  { border-color: transparent; color: #b45309; }
// dyn-btn-accent-green  { border-color: transparent; color: #047857; }
// dyn-btn-accent-purple { border-color: transparent; color: #6d28d9; }
// dyn-btn-accent-pink   { border-color: transparent; color: #be185d; }
// dyn-btn-accent-red    { border-color: transparent; color: #b91c1c; }
// dyn-btn-accent-yellow { border-color: transparent; color: #a16207; }
// dyn-btn-accent-blue   { border-color: transparent; color: #1d4ed8; }
// dyn-btn-accent-teal   { border-color: transparent; color: #0f766e; }

  // Optional: only needed if permission keys don't follow the
  // view_<entity> / manage_<entity> default.
  // roles: { view: 'view_mosyreminders', manage: 'manage_mosyreminders' },
};
