// This is the ONLY file that changes when you clone this module.
// See SCHEMA-SPEC.md for the full reference — quick version below.
// Rough cut auto-generated by db-cli.js (rule-based column-name matching,
// no AI) — hand-tune sections/profileActions/groupedSelect below same as
// any other cloned module.
//
// FRONTEND schema — full UI shape (showInList, profileActions, apiBase,
// rowLinks, customBlocks, sections, moduleRole, etc). The trimmed backend
// counterpart lives alongside this at the api/ path and only carries
// entity/fields/batchMutations/roles.

import { getApiRoutes } from '../AppRoutes/apiRoutesHandler';
import { resolveField } from '../DataControl/imsv2Schema';
// Use default base root (/)
const apiRoutes = getApiRoutes();
const moduleApi = apiRoutes.activities.base;

export const ActivitiesSchema = {
  entity: 'activities',              // DB table name; also drives default role names
                                     // (view_activities / manage_activities) and apiBase
  label: 'Activities',                 // optional, defaults to entity capitalized
  apiBase: moduleApi,

  //api endpint for importing data from csv
  importDataEndpoint : apiRoutes.activities.import,

  // Page-level UI gate — checked once, for the WHOLE grid AND the WHOLE
  // profile/form page, via mosyACTRLHasRole. No moduleRole set -> open to
  // anyone (same additive convention as every other role/flag in this
  // file). This is a different layer than the per-action `role` flag
  // inside individual moduleActions entries below: moduleRole controls
  // whether someone can reach the page at all; a per-action role controls
  // whether one specific button shows up once they're already in. Same
  // UI-only caveat as those: route.js needs the equivalent server-side
  // check for this to be real enforcement, not just hiding.
  moduleRole: 'view_activities',


  gridOptions : {
   checkBoxes : false,
   checkFunction : "gridCheckBoxAction"  
  },

  multiGridRows: [
    // {
    //   key: 'order_items',
    //   parentTable: 'gps_logs',
    //   title: 'Log summary',
    //   columns: [
    //     { key: 'speed', label: 'Speed' },
    //     { key: 'latitude', label: 'Lat' },
    //     { key: 'longitude', label: 'Long' , sum: true},
    //     { key: 'remark', label: 'Selling price' }
    //   ],
    //   viewMoreLink: '../gpslogs/list',
    //   filter: { order_id: '{record_id}' },
    // },
  ],

  rowLinks: [],

  // Actions available from the list view, form and grid in display order.
  //{ 
  // key: 'filter_by_client', -- name of the action 
  // label: 'Filter by account', -- button label 
  // icon: 'user', -- icon of the buttons
  // grid:true, -- show on grid or not, 
  // type: 'action', -- indicates action on form registry 
  // form: false, -- show on form or not, 
  // rowAction: false --show on row drop down or not
  // variant : 'outline-primary', -- button color  variant
  // navigateTo: '/supererpv5/revenueplan/profile', -- route to navigate to -  for link buttons only 
  // colorClass:"bg-success text-white", -- button color classname 
  // confirm: 'Are you sure you want to delete this revenueplan?', -- confirmation message for delete button
  // editOnly: true, -- show on edit only or not
  // role: 'manage_revenueplan' -- role required for this action
  //},

  profileActions: [
    { key: 'back', label: 'Back to list', icon: 'arrow-left', variant: 'outline-secondary', navigateTo: '/imsv2/activities/list', grid: false, form: true },
    { key: 'save', label: 'Save', icon: 'save', variant: 'primary', grid: false, form: true, rowAction: false },
    { key: 'delete', label: 'Delete', icon: 'trash', variant: 'outline-danger', confirm: 'Are you sure you want to delete this activitie?', editOnly: true, grid: false, form: true, rowAction: true, role: 'manage_activities' },
    { key: 'view', label: 'View more', icon: 'edit', rowAction: true },
    { key: 'new', label: 'New Activity', icon: 'plus', variant: 'outline-primary', navigateTo: '/imsv2/activities/profile', grid: true, form: false, rowAction: false },
    { key: 'clone', label: 'Clone Record', icon: 'copy', variant: 'outline-secondary', editOnly: true, grid: false, form: true, rowAction: false, role: 'manage_activities' },
    //{ key: 'filterByDate', label: 'Filter by date', icon: 'calendar', variant: 'outline-primary', type: 'action', grid: true, form: false, rowAction: false },

    // Contact-touch actions — route through logicControl/actionsRegistry.js,
    // which resolves the linked contact's phone/email via contact_id before
    // opening the shared Smart Call / Smart Messenger UI.
    { key: 'call', label: 'Call', icon: 'phone', variant: 'outline-success', type: 'action', editOnly: true, grid: false, form: true, rowAction: true },
    { key: 'send_message', label: 'Send Message', icon: 'comment', variant: 'outline-primary', type: 'action', editOnly: true, grid: false, form: true, rowAction: true },
    { key: 'add_reminder', label: 'Set reminder', icon: 'clock-o', variant: 'outline-primary', type: 'action', editOnly: true, grid: false, form: true },
    { key: 'add_note', label: 'Add Note', icon: 'sticky-note-o', variant: 'outline-warning', type: 'action', editOnly: true, grid: false, form: true },
    { key: 'update_status', label: 'Update Status', icon: 'refresh', variant: 'outline-primary', type: 'action', editOnly: true, grid: false, form: true, rowAction: true },

    // Related-record popups — scoped to this activity's linked contact
    // (call/send_message/set_reminder all resolve/scope by contact_id too).
    { key: 'view_messages', label: 'Messages', icon: 'comments-o', variant: 'outline-secondary', type: 'action', editOnly: true, grid: false, form: true, rowAction: true },
    { key: 'view_calls', label: 'Calls', icon: 'history', variant: 'outline-secondary', type: 'action', editOnly: true, grid: false, form: true, rowAction: true },
    { key: 'view_reminders', label: 'Reminders', icon: 'bell', variant: 'outline-secondary', type: 'action', editOnly: true, grid: false, form: true, rowAction: true },
    { key: 'view_notes', label: 'Notes', icon: 'sticky-note-o', variant: 'outline-secondary', type: 'action', editOnly: true, grid: false, form: true, rowAction: true },

    // Grid-toolbar smart filters — client/deal pick a row from another
    // module and scope by this table's own FK column, status/type pick
    // from this table's own distinct values, date range-filters on the
    // activity date.
    { key: 'filter_by_client', label: 'Filter by Client', icon: 'user', variant: 'outline-secondary', type: 'action', grid: true, form: false, rowAction: false },
    { key: 'filter_by_deal', label: 'Filter by Deal', icon: 'handshake-o', variant: 'outline-secondary', type: 'action', grid: true, form: false, rowAction: false },
    { key: 'filter_by_status', label: 'Filter by Status', icon: 'filter', variant: 'outline-secondary', type: 'action', grid: true, form: false, rowAction: false },
    { key: 'filter_by_date', label: 'Filter by Date', icon: 'calendar', variant: 'outline-secondary', type: 'action', grid: true, form: false, rowAction: false },
    { key: 'filter_by_type', label: 'Filter by Type', icon: 'tag', variant: 'outline-secondary', type: 'action', grid: true, form: false, rowAction: false },
  ],



  // customBlocks — the escape hatch for UI that doesn't fit the rigid
  // field-grid: a raw component, handed the SAME values/setValue/errors/
  // schema/isEditing/row context a real field gets. A block's `key` just
  // sits in a section's `fields` array exactly like a real field key —
  // wherever it appears there is where it renders. Empty by default;
  // uncomment and point at a real component when a field needs custom UI
  // (see SCHEMA-SPEC.md for the full pattern, e.g. companies/schema.js).
  customBlocks: [
    // { key: 'some_field', component: SomeComponent, colSpan: 7 },
  ],

  fieldGroups: [],
  // Field keys shown as columns in list view, in display order.
  showInList: ['row_count', 'contact_name', 'status', 'title', 'type', 'description', 'outcome',  'activity_date', 'tag'],

  //export columns these columns are used to generate upload csv template file
  exportColumns: ['contact_id', 'opportunity_id', 'type', 'direction', 'subject', 'description', 'activity_date', 'tag'],

  sections: [
    { key: 'basic_information', label: 'Basic Information', columns: 3, fields: [ 'contact_id', 'opportunity_id', 'subject',  'type', 'activity_date', 'tag', 'status',  'description', 'outcome'] },
    { key: 'other_details', label: 'Other Details', columns: 3, fields: ['end_date', 'venue', 'agenda', 'related_record_id', 'reg_date'] },
  ],

  fields: [
    // key: DB column name | label: shown on screen | type: drives input + SQL type
    { key: 'primkey', label: 'Primkey', type: 'number', system: true, editable: false },
    { key: 'activity_id', label: 'Activity Id', type: 'text', system: true, editable: false },
    ...resolveField('contact_id', { as: 'contact_name' }),
    ...resolveField('opportunity_id', { as: 'title' }),
    { key: 'type', label: 'Type', type: 'select', title: true, options: ['Meet', 'Follow Up', 'Call', 'Message', 'Task'] },
    { key: 'title', label: 'Title', type: 'text' , title:true },
    { key: 'direction', label: 'Direction', type: 'text' },
    { key: 'contact_name', label: 'Contact', type: 'text', title:true },
    { key: 'subject', label: 'Subject', type: 'text' , colSpan: 8},
    { key: 'description', label: 'Description', type: 'textarea', colSpan: 12 },
    { key: 'activity_date', label: 'Activity Date', type: 'datetime' },
    { key: 'tag', label: 'Tag', type: 'groupedSelect', endpoint: moduleApi, groupByField: 'tag', colSpan: 4 },
    { key: 'end_date', label: 'End Date', type: 'datetime' },
    { key: 'venue', label: 'Venue', type: 'groupedSelect', endpoint: moduleApi , colSpan : 8 },
    { key: 'agenda', label: 'Agenda', type: 'textarea', colSpan :12 },
    { key: 'outcome', label: 'Outcome', type: 'textarea', colSpan :12 },
    { key: 'status', label: 'Status', type: 'select', options: ['Done', 'Not done', 'Cancelled'], title: true },
    // Generic reverse pointer (same convention as mosy_reminders.related_record_id)
    // used by other modules with no real FK back to activities — e.g. income
    // plan's add_activity/view_activities scope by this instead of the older
    // tag-matching hack. Not tied to one specific target table.
    { key: 'related_record_id', label: 'Related Record Id', type: 'text', editable: false, colSpan: 4 },
    { key: 'reg_date', label: 'Date created', type: 'datetime', editable: false },
    { key: 'row_count', label: '#', type: 'number', computed: true, editable: false },
    //  live search field sample 
    // { key: 'permissions', label: 'Permissions',
    //   type: 'liveSearch', colSpan: 6,
    //   endpoint: '/api/assetguard/systemmodules',
    //   searchTable: 'system_modules',
    //   valueField: 'record_id',      // id column on system_modules
    //   displayField: 'module_name',  // label column on system_modules — what search results/defaultValue text actually render
    //   labelKey: 'permission_name',  // cached label already joined onto THIS row (system_roles) — only used to seed defaultValue on load
    // },
    // more fields... see SCHEMA-SPEC.md for the full field option list
    // (searchable, editable, options, priority, db overrides)
  ],

  filters: [
    { key: 'all', label: 'All', query: {} },
  ],

  actions: [
    // { key: 'some_action', label: 'Do Something', appliesTo: { status: 'x' } },
    // "key" must match a function registered in lib/actionsRegistry.js
  ],

// for button color classes  
// dyn-btn-accent-amber  { border-color: transparent; color: #b45309; }
// dyn-btn-accent-green  { border-color: transparent; color: #047857; }
// dyn-btn-accent-purple { border-color: transparent; color: #6d28d9; }
// dyn-btn-accent-pink   { border-color: transparent; color: #be185d; }
// dyn-btn-accent-red    { border-color: transparent; color: #b91c1c; }
// dyn-btn-accent-yellow { border-color: transparent; color: #a16207; }
// dyn-btn-accent-blue   { border-color: transparent; color: #1d4ed8; }
// dyn-btn-accent-teal   { border-color: transparent; color: #0f766e; }

  // Optional: only needed if permission keys don't follow the
  // view_<entity> / manage_<entity> default.
  // roles: { view: 'view_activities', manage: 'manage_activities' },
};
