// Auto-generated by db-cli.js — BACKEND schema (trimmed).
// This is the data-shape-only counterpart to the frontend schema.js at the
// matching app/ path. It intentionally does NOT include showInList,
// profileActions, apiBase, rowLinks, customBlocks, sections, moduleRole,
// filters, or actions — those are UI concerns and live in the frontend
// schema only. Field entries also omit `label` here (UI-only display
// text) even though the frontend fields carry it. Edit
// fields/batchMutations/roles here; edit everything else there. Keep the
// `fields` array in sync between the two by regenerating both together
// (this tool writes both from the same column read).

export const MosymetricsSchema = {
  entity: 'mosy_metrics',

  moduleRole: 'view_mosy_metrics',

  fields: [
    // key: DB column name | type: drives SQL/validation (label omitted —
    // UI-only, lives in the frontend schema)
    { key: 'primkey', type: 'number', system: true, editable: false },
    { key: 'metric_id', type: 'text', system: true, editable: false },
    { key: 'app_name', type: 'text', title: true, required: true, searchable: true },
    { key: 'metric_key', type: 'text', searchable: true },
    { key: 'label', type: 'text', searchable: true },
    { key: 'sql_query', type: 'textarea', searchable: true },
    { key: 'db_connection_key', type: 'text', searchable: true },
    { key: 'status', type: 'groupedSelect', endpoint: '/api/imsv2/mosymetrics/list', groupByField: 'status', searchable: true },
    { key: 'reg_date', type: 'datetime' },
    { key: 'hive_site_id', type: 'text', searchable: true },
    { key: 'row_count', type: 'number', computed: true, editable: false },
  ],

  // Optional: joins enriching each row with data from another table.
  // Same shape as your existing *BatchMutations.js files.
  batchMutations: {
    // "_staff_full_name_staff_id": {
    //   type: "join", table: "staff", link: "staff_id:record_id",
    //   select: { "_staff_full_name_staff_id": "full_name" }
    // },
  },

  roles: { view: 'view_mosymetrics', manage: 'manage_mosymetrics' },
};
